"""Prologue and Sumatra maps."""
from content.maphelp import M, rect, line, blob, obj, ix, npc, lm, ex, find

# =============================================================== PROLOGUE
M("desa_awal", "Kampung Awal", "prologue", (48, 36), "prologue", "waves",
  {"default": "GRASS",
   "rects": [rect("SAND", 0, 30, 48, 6), rect("PAVING", 17, 15, 14, 10),
             rect("PATH", 22, 4, 4, 12), rect("RICE", 34, 24, 10, 6),
             rect("WATER", 0, 34, 48, 2)],
   "lines": [line("PATH", 5, 20, 43, 20, 3), line("PATH", 24, 20, 24, 33, 3),
             line("PATH", 12, 20, 12, 27, 2)],
   "blobs": [blob("JUNGLE", 6, 8, 5), blob("JUNGLE", 42, 8, 5)]},
  objects=[obj("hut_coastal", 12, 14), obj("hut_coastal", 36, 14),
           obj("warung", 10, 24), obj("lumbung", 40, 26),
           obj("workshop", 38, 32), obj("market_stall", 18, 34),
           obj("boat_dock_house", 6, 30, flip=False),
           obj("canoe", 9, 33), obj("dock", 12, 33),
           obj("well", 20, 22), obj("signpost", 24, 26),
           obj("basket", 16, 24), obj("drying_rack", 30, 30),
           obj("fence", 32, 22), obj("fence", 33, 22),
           obj("tree_palm", 4, 12), obj("tree_palm2", 44, 16),
           obj("tree_tropical", 2, 22), obj("bush_flower", 28, 24),
           obj("flower_patch", 26, 28), obj("brazier", 22, 18),
           obj("pot_plant", 14, 20), obj("crate", 34, 34)],
  npcs=[npc("npc_penjaga", 22, 19, facing="down"),
        npc("npc_pengembara", 27, 22, wander=True),
        npc("npc_anak", 30, 21, wander=True),
        npc("npc_guru", 15, 21, facing="right"),
        npc("npc_pengrajin", 34, 31, facing="left", wander=True)],
  landmarks=[lm("lm_kampung_awal", "Kampung Awal", 24, 22,
                "The home village: one street, one jetty, and a store room full of memories.",
                "camp")],
  interactables=[
      ix("pg_store_room", "door", 12, 15, prompt="Enter the store room",
         target="desa_awal", entry="store"),
      ix("pg_sign_gate", "sign", 24, 27, title="Village board",
         text="Kampung Awal. Jetty to the west, rice field east, road inland north."),
      ix("pg_note_pages", "note", 22, 22, title="Grandmother's first page",
         text="It is not one culture, and it is not a hundred separate ones either. "
              "Write down what people tell you, in their own words."),
      ix("pg_save", "save", 20, 21),
      ix("pg_col_basket", "pickup", 16, 25, target="keranjang_bahu",
         text="A woven shoulder basket, left on the bench."),
      ix("pg_minigame_fest", "minigame", 28, 33, prompt="Join the village game",
         minigame="nod", title="Festival Timing", target="nod",
         text="Stop the marker in the golden band, three rounds.",
         data={"rounds": 3, "width": 100, "speed": 300,
               "themes": ["the boat race is starting!", "the drums are getting louder!",
                          "everybody is watching the finish!"]},
         reward_cp=35)],
  collision=[[0, 36, 48, 2]])

M("pantai_awal", "Pantai Awal", "prologue", (48, 34), "prologue", "waves",
  {"default": "SAND",
   "rects": [rect("WATER", 0, 0, 48, 8), rect("WATER", 0, 8, 3, 26),
             rect("GRASS", 12, 12, 36, 22), rect("PATH", 14, 18, 34, 3)],
   "blobs": [blob("REED", 38, 26, 4), blob("JUNGLE", 44, 12, 5)]},
  objects=[obj("boat_dock_house", 20, 14), obj("dock", 24, 10), obj("canoe", 27, 9),
           obj("canoe", 31, 10, flip=True), obj("drying_rack", 16, 22),
           obj("drying_rack_blue", 19, 22), obj("basket", 34, 20),
           obj("crate", 36, 21), obj("barrel", 38, 22),
           obj("tree_palm", 14, 30), obj("tree_palm2", 30, 31),
           obj("rock_big", 44, 30), obj("rock_small", 42, 28),
           obj("reed_clump", 40, 28), obj("fence_wood", 12, 18)],
  npcs=[npc("npc_nelayan", 22, 20, facing="down")],
  landmarks=[lm("lm_pantai_awal", "The Old Jetty", 24, 12,
                "Planks worn smooth by forty years of bare feet and wet rope.", "jetty")],
  interactables=[
      ix("pg_net_bench", "note", 18, 22, title="The mending bench",
         text="Twine, a wooden shuttle and a bamboo needle. Nothing metal in sight - "
              "a net is tied, never nailed."),
      ix("pg_pick_net", "pickup", 19, 23, target="benang_jaring",
         text="A roll of tough net twine."),
      ix("pg_beach_shell", "pickup", 40, 24, target="col_kerang"),
      ix("pg_save_beach", "save", 26, 22),
      ix("pg_hidden_rockpool", "hidden", 44, 32, title="Rock Pools",
         text="Behind the rocks the tide has left a shallow pool, warm as bathwater, "
              "full of small bright fish.",
         items=["air_minum"], culture="kampung_home")],
  collision=[])

M("prologue_festival", "Lapangan Festival", "prologue", (40, 30), "victory", "night_crickets",
  {"default": "GRASS",
   "rects": [rect("PAVING", 8, 8, 24, 16), rect("PATH", 4, 15, 32, 3),
             rect("CARPET", 16, 12, 8, 8)],
   "blobs": [blob("JUNGLE", 4, 26, 4), blob("JUNGLE", 36, 26, 4)]},
  objects=[obj("stage", 20, 10), obj("brazier", 12, 12), obj("brazier", 28, 12),
           obj("brazier", 12, 20), obj("brazier", 28, 20),
           obj("market_stall", 8, 26), obj("market_stall_blue", 32, 26),
           obj("gamelan_set", 14, 16), obj("angklung_stand", 26, 16),
           obj("drum", 20, 22), obj("lantern", 16, 8), obj("lantern", 24, 8),
           obj("fence", 6, 24), obj("fence", 34, 24),
           obj("tree_pine", 2, 6), obj("tree_fruit", 38, 6)],
  npcs=[npc("npc_penjaga", 20, 14, facing="down"),
        npc("npc_penari", 24, 18, wander=True),
        npc("npc_koki", 12, 24, facing="right"),
        npc("npc_pedagang", 30, 24, facing="left", wander=True),
        npc("npc_anak", 18, 24, wander=True),
        npc("npc_pengembara", 28, 20, facing="left")],
  landmarks=[lm("lm_lapangan", "Festival Ground", 20, 16,
                "Where every region's music ended up in the same evening.", "festival")],
  interactables=[
      ix("pg_fest_sign", "sign", 16, 26, title="Festival banner",
         text="One evening, six islands, everybody welcome. Bring something to share."),
      ix("pg_fest_minigame", "minigame", 24, 12, prompt="Play the festival game",
         minigame="nod", title="Festival Finale", target="nod",
         text="Three rounds, faster each time. The crowd is on your side.",
         data={"rounds": 3, "width": 90, "speed": 330,
               "themes": ["the gongs are warming up!", "the crowd is clapping!",
                          "one more round!"]},
         reward_cp=40),
      ix("pg_fest_ending", "dialogue", 20, 16, target="ending_finale",
         prompt="Close the notebook"),
      ix("pg_fest_save", "save", 14, 20)],
  collision=[])

# ================================================================ SUMATRA
M("sumatra_desa", "Kampung Danau", "sumatra", (48, 40), "sumatra", "stream",
  {"default": "GRASS",
   "rects": [rect("HIGHLAND", 0, 0, 48, 6), rect("PAVING", 16, 16, 16, 12),
             rect("RICE", 2, 26, 12, 10), rect("DIRT", 30, 26, 14, 8),
             rect("WATER", 0, 38, 48, 2)],
   "lines": [line("PATH", 4, 22, 44, 22, 3), line("PATH", 24, 6, 24, 22, 3),
             line("PATH", 24, 22, 24, 36, 3)],
   "blobs": [blob("TALLGRASS", 40, 8, 5), blob("JUNGLE", 4, 8, 4)]},
  objects=[obj("rumah_gadang", 24, 10), obj("lumbung", 12, 14), obj("lumbung", 36, 14),
           obj("warung", 10, 24), obj("market_stall", 16, 30),
           obj("workshop", 38, 28), obj("stage", 24, 32), obj("pot_plant", 20, 16),
           obj("well", 22, 20), obj("drying_rack", 30, 30), obj("loom", 34, 30),
           obj("basket", 28, 28), obj("signpost", 24, 24),
           obj("tree_tropical", 2, 16), obj("tree_fruit", 44, 20),
           obj("bamboo_cluster", 42, 34), obj("flower_patch2", 18, 26),
           obj("fence_wood", 14, 32), obj("brazier", 26, 18),
           obj("textile_rack_red", 32, 34), obj("statue", 18, 14)],
  npcs=[npc("npc_aminah", 22, 17, facing="down"),
        npc("npc_ida", 16, 24, facing="right"),
        npc("npc_sari", 34, 30, facing="left"),
        npc("npc_datuak", 26, 20, facing="down"),
        npc("npc_penari", 26, 28, facing="up", wander=True)],
  landmarks=[lm("lm_rumah_gadang", "Rumah Gadang", 24, 14,
                "The clan house of the women's line, its roof sweeping up to two sharp points.",
                "house"),
             lm("lm_pasar_danau", "Highland Market", 16, 30,
                "A market street that smells of coffee, chilli and rain.")],
  interactables=[
      ix("sm_carving_wall", "puzzle", 26, 12, target="pz_carving_memory",
         prompt="Examine the stacked panels",
         when={"quest_active": "sm_01_kampung"}, sprite="easel_board"),
      ix("sm1_lm_note", "note", 24, 15, title="The gable",
         text="The roof rises into two sharp points. The house belongs to the women of the clan, "
              "and it is theirs to pass on."),
      ix("sm_pick_milk", "pickup", 30, 31, target="mentega_kelapa",
         text="A bowl of thick coconut milk, still warm from the grinding stone."),
      ix("sm_pick_plates", "pickup", 22, 30, target="piring_tari",
         text="Two small dance plates, stacked on the mat."),
      ix("sm_col_songket_thread", "pickup", 36, 30, target="col_benang_emas"),
      ix("sm_pick_spice", "pickup", 14, 30, target="bumbu_rendang",
         text="Chilli, ginger, turmeric, galangal and lemongrass bundled in banana leaf."),
      ix("sm_pick_thread", "pickup", 18, 30, target="benang_songket",
         text="A spool of shiny thread for laying over cloth."),
      ix("sm_col_carving", "pickup", 34, 32, target="col_ukiran_kecil"),
      ix("sm_col_talempong", "pickup", 12, 16, target="col_talempong_chip"),
      ix("sm_rumah_hidden", "hidden", 44, 36, title="Behind the Bamboo",
         text="A narrow gap in the bamboo leads to a small clearing with a stone seat "
              "worn smooth by generations of storytellers.",
         items=["biji_kopi"], culture="ukiran_dayak"),
      ix("sm_save_village", "save", 20, 22),
      ix("sm_sign_road", "sign", 24, 25, title="Road sign",
         text="North: the lake road. West: the rainforest. East: the market street."),
      ix("sm_festival", "minigame", 24, 34, prompt="Play the harvest game",
         minigame="nod", title="Harvest Timing", target="nod",
         text="Bring in the harvest on the beat.",
         data={"rounds": 3, "width": 96, "speed": 310,
               "themes": ["the harvest is starting!", "the drums speed up!",
                          "one more round, then we eat!"]},
         reward_cp=35)],
  collision=[[0, 0, 48, 6]])

M("sumatra_hutan", "Hutan Hujan", "sumatra", (54, 40), "sumatra", "forest",
  {"default": "JUNGLE",
   "rects": [rect("TALLGRASS", 6, 6, 42, 6), rect("PATH", 4, 20, 46, 3),
             rect("WATER", 34, 16, 4, 18), rect("MUD", 10, 26, 14, 10)],
   "blobs": [blob("GRASS", 30, 32, 7), blob("BAMBOO", 44, 8, 5), blob("REED", 20, 18, 4)]},
  objects=[obj("tree_tropical", 8, 10), obj("tree_tropical2", 14, 8), obj("tree_tropical", 22, 10),
           obj("tree_fruit", 30, 8), obj("tree_tropical2", 40, 12), obj("tree_tropical", 48, 16),
           obj("tree_tropical", 6, 30), obj("tree_fruit", 18, 34), obj("tree_tropical2", 44, 34),
           obj("bamboo_cluster", 42, 10), obj("bamboo_cluster", 46, 14),
           obj("fern", 12, 18), obj("fern", 28, 24), obj("bush_green", 16, 22),
           obj("bush_dark", 38, 26), obj("mushroom", 24, 30), obj("log", 32, 28),
           obj("rock_big", 46, 24), obj("cave_mouth", 12, 12), obj("waterfall", 36, 18),
           obj("bridge_plank", 34, 24), obj("reed_clump", 22, 20)],
  npcs=[npc("npc_bujang", 30, 30, facing="up")],
  landmarks=[lm("lm_hutan_sumatra", "Rainforest Clearing", 30, 30,
                "Bamboo, mud and water noise. Somebody has been cutting flute blanks here.",
                "clearing")],
  interactables=[
      ix("sm_flute_bench", "pickup", 32, 30, target="bambu_saluang",
         text="A bamboo tube, cut to length, lying on a stump beside a knife."),
      ix("sm_pz_saluang_site", "puzzle", 30, 32, target="pz_saluang_song",
         prompt="Try the flute", sprite="flute_rack",
         when={"quest_active": "sm_03_saluang"}),
      ix("sm_cave_note", "note", 12, 13, title="Cave mouth",
         text="Cool air comes out of the dark. Charcoal marks on the rock are old, and "
              "the people who made them are not named here."),
      ix("sm_col_coffee", "pickup", 26, 36, target="col_kopi_liar"),
      ix("sm_hutan_hidden", "hidden", 46, 30, title="The Fallen Tree Bridge",
         text="A tree has fallen across the stream and made a bridge. The far bank is "
              "quieter, and the birds there are not used to people.",
         items=["obat_herbal"], culture="hutan_kalimantan"),
      ix("sm_save_hutan", "save", 28, 28),
      ix("sm_bark_note", "note", 36, 26, title="Bark inscription",
         text="Original marks cut into the bark: three lines, a hook and a dot. The shape "
              "is repeated in this game's artwork as an invented motif, not a copy of any "
              "specific carving.")],
  collision=[])

M("sumatra_danau", "Tepi Danau Toba", "sumatra", (54, 40), "sumatra", "waves",
  {"default": "GRASS",
   "rects": [rect("WATER", 0, 0, 54, 14), rect("SAND", 0, 14, 54, 5),
             rect("HIGHLAND", 0, 30, 54, 10), rect("PATH", 6, 22, 44, 3),
             rect("PAVING", 20, 24, 14, 8)],
   "blobs": [blob("REED", 12, 20, 5), blob("CLIFF", 44, 24, 5), blob("TALLGRASS", 28, 34, 6)]},
  objects=[obj("hut_coastal", 16, 28), obj("warung", 30, 28), obj("market_stall", 24, 32),
           obj("canoe", 10, 16), obj("canoe", 14, 16, flip=True), obj("dock", 20, 17),
           obj("drying_rack", 34, 24), obj("drying_rack_blue", 37, 24),
           obj("basket", 22, 30), obj("crate", 20, 31), obj("barrel", 18, 31),
           obj("rock_big", 46, 20), obj("rock_small", 42, 20), obj("rock_small", 44, 22),
           obj("reed_clump", 10, 20), obj("tree_pine", 4, 26), obj("tree_pine", 48, 32),
           obj("lookout_tower", 40, 28), obj("fence_wood", 6, 24)],
  npcs=[npc("npc_pedagang", 24, 28, facing="down", wander=True),
        npc("npc_nelayan", 12, 22, facing="right")],
  landmarks=[lm("lm_danau_toba", "Lake Viewpoint", 40, 27,
                "A lookout above the water: the largest volcanic lake in the world, ringed "
                "by highland slopes.", "lake")],
  interactables=[
      ix("sm_pz_lake_site", "puzzle", 12, 21, target="pz_danau_search",
         prompt="Search the shore", sprite="basket",
         when={"quest_active": "sm_06_danau"}),
      ix("sm_lake_note", "note", 22, 18, title="Jetty notice",
         text="Canoes leave at first light. Nobody crosses the lake in the afternoon wind."),
      ix("sm_col_coffee2", "pickup", 30, 33, target="col_kopi_liar"),
      ix("sm_coffee_sack", "pickup", 26, 30, target="biji_kopi",
         text="A sack of green coffee beans, drying in the sun."),
      ix("sm_lake_hidden", "hidden", 50, 36, title="Under the Cliff",
         text="A shelf of rock keeps the rain off. Someone has left dry firewood and a "
              "folded blanket here, ready for the next traveller.",
         items=["bekal_jalan"], culture="danau_toba"),
      ix("sm_save_lake", "save", 20, 26),
      ix("sm_lake_minigame", "minigame", 16, 26, prompt="Play the boat-song game",
         minigame="nod", title="Boat Song Timing", target="nod",
         text="Paddle in time with the song.",
         data={"rounds": 3, "width": 100, "speed": 320,
               "themes": ["the paddles are up!", "the song speeds up!",
                          "one more push to the shore!"]},
         reward_cp=35)],
  collision=[])
