"""Java, Kalimantan, Sulawesi and Papua maps."""
from content.maphelp import M, rect, line, blob, obj, ix, npc, lm, ex, find

# ==================================================================== JAVA
M("java_desa", "Desa Jawa", "java", (48, 40), "java", "village",
  {"default": "GRASS",
   "rects": [rect("RICE", 0, 4, 18, 14), rect("RICE", 30, 4, 18, 14),
             rect("PAVING", 16, 18, 16, 12), rect("WATER", 0, 38, 48, 2),
             rect("PATH", 8, 24, 32, 3)],
   "lines": [line("PATH", 24, 6, 24, 24, 3), line("PATH", 24, 24, 24, 36, 3),
             line("PATH", 4, 24, 44, 24, 3)],
   "blobs": [blob("JUNGLE", 44, 34, 4)]},
  objects=[obj("joglo_house", 22, 12), obj("joglo_house_small", 12, 14),
           obj("joglo_house_small", 36, 14), obj("lumbung", 6, 20), obj("lumbung", 42, 20),
           obj("warung", 14, 28), obj("warung_green", 34, 28),
           obj("cultural_center", 24, 34), obj("stage", 20, 20),
           obj("gamelan_set", 26, 20), obj("angklung_stand", 28, 22),
           obj("well", 18, 22), obj("pot_plant", 22, 22), obj("basket", 30, 24),
           obj("textile_rack", 32, 32), obj("loom", 30, 32),
           obj("drying_rack", 12, 32), obj("rice_terrace_edge", 8, 6),
           obj("rice_terrace_edge", 38, 6), obj("tree_pine", 2, 30),
           obj("bamboo_cluster", 44, 26), obj("shrine_java", 6, 14),
           obj("fence_wood", 16, 30)],
  npcs=[npc("npc_ki_bagus", 26, 21, facing="down"),
        npc("npc_mbah_karto", 22, 20, facing="right"),
        npc("npc_dewi", 14, 28, facing="right"),
        npc("npc_rara", 30, 22, facing="left", wander=True)],
  landmarks=[lm("lm_joglo", "Village Hall", 24, 30,
                "A tall joglo roof over an open hall: the pendopo where the gamelan is kept.",
                "hall"),
             lm("lm_kampung_jawa", "Rice Village", 24, 24,
                "A village laid out between two blocks of wet rice fields.")],
  interactables=[
      ix("jv_gamelan_site", "puzzle", 26, 22, target="pz_gamelan",
         prompt="Join the rehearsal", sprite="gamelan_set",
         when={"quest_active": "jv_03_gamelan"}),
      ix("jv_angklung_site", "puzzle", 30, 24, target="pz_angklung_order",
         prompt="Look at the angklung", sprite="angklung_stand",
         when={"quest_active": "jv_06_angklung"}),
      ix("jv_pick_mallet", "pickup", 20, 20, target="tabuh",
         text="A padded mallet for the bronze."),
      ix("jv_pick_canting", "pickup", 32, 30, target="canting",
         text="A small copper wax pen with a bamboo handle."),
      ix("jv_pick_script", "pickup", 18, 30, target="naskah_wayang",
         text="A page of cues and jokes, written for a night performance."),
      ix("jv_col_wax", "pickup", 34, 24, target="col_lilin"),
      ix("jv_col_puppet", "pickup", 24, 32, target="col_boneka_lidi"),
      ix("jv_save_village", "save", 20, 24),
      ix("jv_sign_roads", "sign", 24, 27, title="Road sign",
         text="North: the temple grounds. East: the morning market. West: the terraces."),
      ix("jv_hidden_pond", "hidden", 44, 36, title="The Hidden Pond",
         text="Behind the bamboo there is a small pond with lotus leaves and a stone "
              "stair going down. Somebody washes the gamelan here after the rain.",
         items=["pipa_bambu"], culture="sawah"),
      ix("jv_village_game", "minigame", 20, 22, prompt="Join the evening game",
         minigame="nod", title="Evening Timing", target="nod",
         text="The gamelan plays; keep the beat.",
         data={"rounds": 3, "width": 96, "speed": 315,
               "themes": ["the bonang starts!", "the drums come in!",
                          "the gong is waiting!"]},
         reward_cp=35)],
  collision=[])

M("java_sawah", "Terasering Sawah", "java", (54, 40), "java", "stream",
  {"default": "GRASS",
   "rects": [rect("RICE", 4, 4, 46, 10), rect("RICE", 4, 16, 34, 10),
             rect("RICE", 4, 28, 22, 8), rect("WATER", 0, 0, 54, 2),
             rect("GRASS", 40, 28, 14, 10), rect("PATH", 6, 14, 44, 2)],
   "lines": [line("PATH", 6, 14, 50, 14, 2), line("PATH", 6, 26, 50, 26, 2),
             line("PATH", 48, 26, 48, 14, 2)],
   "blobs": [blob("REED", 30, 22, 4), blob("JUNGLE", 50, 34, 4)]},
  objects=[obj("rice_terrace_edge", 8, 12), obj("rice_terrace_edge", 20, 12),
           obj("rice_terrace_edge", 32, 12), obj("rice_terrace_edge", 44, 12),
           obj("rice_terrace_edge", 12, 24), obj("rice_terrace_edge", 28, 24),
           obj("rice_terrace_edge", 12, 32), obj("hut_coastal", 44, 30),
           obj("lumbung", 36, 34), obj("drying_rack", 42, 34),
           obj("cooking_fire", 46, 34), obj("well", 20, 30),
           obj("tree_palm", 2, 26), obj("tree_pine", 50, 6),
           obj("reed_clump", 30, 20), obj("bridge_plank", 26, 14),
           obj("bush_green", 24, 30), obj("flower_patch", 34, 32),
           obj("signpost", 8, 16)],
  npcs=[npc("npc_pak_tarno", 42, 32, facing="left")],
  landmarks=[lm("lm_sawah", "The Terraces", 26, 20,
                "Stepped wet rice fields fed by shared channels that everybody maintains.",
                "terraces")],
  interactables=[
      ix("jv_pz_water_site", "puzzle", 26, 16, target="pz_sawah_water",
         prompt="Examine the irrigation gate", sprite="bridge_plank",
         when={"quest_active": "jv_04_sawah"}),
      ix("jv_pick_seedlings", "pickup", 44, 32, target="bibit_padi",
         text="Bundles of young rice plants, tied with grass."),
      ix("jv_col_temple_stone", "pickup", 48, 30, target="col_batu_candi"),
      ix("jv_note_ducks", "note", 20, 30, title="Duck keeper's note",
         text="After the harvest the ducks come through the field and eat what is left. "
              "They leave the field fertilised. Neither of us planned it; both of us like it."),
      ix("jv_save_sawah", "save", 8, 16),
      ix("jv_sawah_hidden", "hidden", 52, 38, title="The Spring",
         text="At the top of the terraces a spring comes out of the hillside. It is the "
              "beginning of every channel below.",
         items=["air_minum"], culture="sawah")],
  collision=[])

M("java_pasar", "Pasar Pagi", "java", (44, 34), "java", "village",
  {"default": "PAVING",
   "rects": [rect("GRASS", 0, 26, 44, 8), rect("PATH", 4, 16, 36, 4),
             rect("DIRT", 0, 30, 44, 4), rect("WATER", 44, 0, 2, 34)],
   "lines": [line("PAVING", 22, 4, 22, 30, 4)],
   "blobs": [blob("JUNGLE", 40, 30, 4)]},
  objects=[obj("market_stall", 10, 12), obj("market_stall_blue", 16, 12),
           obj("market_stall", 22, 12), obj("market_stall_blue", 28, 12),
           obj("market_stall", 34, 12), obj("warung", 8, 22), obj("warung_green", 14, 22),
           obj("food_stall", 26, 22), obj("food_stall", 32, 22),
           obj("clock_tower", 22, 30), obj("crate", 12, 18), obj("barrel", 18, 18),
           obj("basket", 24, 18), obj("pot_plant", 30, 18), obj("easel_board", 36, 18),
           obj("lantern", 20, 10), obj("lantern", 24, 10), obj("tree_fruit", 4, 28),
           obj("bamboo_cluster", 40, 22)],
  npcs=[npc("npc_koki", 26, 22, facing="down"),
        npc("npc_pengrajin", 34, 14, facing="down"),
        npc("npc_pedagang", 12, 20, wander=True, facing="right"),
        npc("npc_pengembara", 30, 26, facing="up")],
  landmarks=[lm("lm_pasar_pagi", "Morning Market", 22, 24,
                "Stalls that open before sunrise and pack up by noon.", "market")],
  interactables=[
      ix("jv_pick_spice", "pickup", 12, 14, target="bumbu_tumpeng",
         text="Turmeric, coconut and aromatics, bundled for a celebration."),
      ix("jv_pick_wax", "pickup", 18, 14, target="lilin_batik",
         text="A block of batik wax, faintly perfumed with resin."),
      ix("jv_pz_jv_market", "puzzle", 22, 18, target="pz_javanese_market",
         prompt="Help at the market", when={"quest_active": "jv_08_pasar_java"}),
      ix("jv_pick_angklung_sou", "pickup", 28, 18, target="sou_angklung_mini"),
      ix("jv_col_key_plate", "pickup", 36, 22, target="col_keping_gamelan"),
      ix("jv_save_market", "save", 20, 24),
      ix("jv_sign_market", "sign", 22, 26, title="Market rules",
         text="Stalls are laid out the night before by the trader whose name is on the list. "
              "If the list is wrong, the whole morning is wrong.")],
  collision=[])

M("java_candi", "Candi Tua", "java", (50, 38), "java", "forest",
  {"default": "GRASS",
   "rects": [rect("TEMPLE", 14, 8, 22, 20), rect("PAVING", 18, 12, 14, 12),
             rect("STONE", 12, 6, 26, 26), rect("PATH", 22, 28, 6, 8),
             rect("JUNGLE", 0, 0, 12, 38), rect("JUNGLE", 38, 0, 12, 38)],
   "blobs": [blob("JUNGLE", 6, 20, 6), blob("TALLGRASS", 44, 30, 5)]},
  objects=[obj("candi", 24, 12), obj("statue", 18, 16), obj("statue", 30, 16),
           obj("shrine", 24, 24), obj("brazier", 16, 22), obj("brazier", 32, 22),
           obj("easel_board", 20, 20), obj("crate", 30, 20),
           obj("tree_tropical", 2, 6), obj("tree_tropical2", 46, 6),
           obj("tree_pine", 2, 30), obj("tree_tropical", 46, 32),
           obj("fern", 14, 30), obj("fern", 34, 30), obj("rock_big", 38, 24),
           obj("flower_patch2", 26, 28), obj("lookout_tower", 40, 34),
           obj("fence", 14, 32)],
  npcs=[npc("npc_penjaga", 26, 26, facing="up")],
  landmarks=[lm("lm_candi", "The Stepped Temple", 24, 18,
                "A ninth-century Buddhist temple built as a stepped mountain; pilgrims "
                "walk clockwise up through the galleries.", "temple")],
  interactables=[
      ix("jv_pz_candi_site", "puzzle", 22, 20, target="pz_candi_relief",
         prompt="Examine the relief panels", sprite="easel_board",
         when={"quest_active": "jv_07_candi"}),
      ix("jv_note_candi", "note", 26, 24, title="Stone notice",
         text="Walk clockwise. Climb slowly: the terraces are the story. "
              "Do not touch the panels - copying is enough."),
      ix("jv_pick_temple", "pickup", 32, 22, target="col_batu_candi"),
      ix("jv_pz_wayang_site", "puzzle", 24, 26, target="pz_wayang_quiz",
         prompt="Sit in the shadow of the shrine", when={"quest_active": "jv_05_wayang"}),
      ix("jv_save_candi", "save", 24, 30),
      ix("jv_hidden_carving", "hidden", 46, 34, title="Masons' Marks",
         text="On the back of a loose stone there are small marks that never appear "
              "on the temple walls - the notes the builders made while they worked.",
         items=["col_batu_candi"], culture="borobudur")],
  collision=[])

# ============================================================= KALIMANTAN
M("kalimantan_desa", "Kampung Sungai", "kalimantan", (50, 38), "kalimantan", "stream",
  {"default": "GRASS",
   "rects": [rect("WATER", 0, 0, 50, 6), rect("SAND", 0, 6, 50, 3),
             rect("PLANK", 12, 12, 28, 16), rect("DIRT", 12, 30, 28, 6),
             rect("PATH", 6, 20, 40, 3), rect("JUNGLE", 0, 22, 10, 16),
             rect("JUNGLE", 40, 22, 10, 16)],
   "lines": [line("PATH", 6, 20, 46, 20, 3), line("PATH", 25, 8, 25, 20, 3)],
   "blobs": [blob("REED", 10, 34, 4), blob("JUNGLE", 45, 34, 5)]},
  objects=[obj("rumah_panjang", 24, 12), obj("drying_rack", 14, 26),
           obj("drying_rack_blue", 17, 26), obj("loom", 30, 28),
           obj("textile_rack_red", 33, 28), obj("canoe", 10, 8), obj("canoe", 14, 8, flip=True),
           obj("dock", 20, 8), obj("well", 20, 20), obj("basket", 28, 20),
           obj("cooking_fire", 16, 30), obj("pot_plant", 22, 18),
           obj("tree_tropical", 4, 12), obj("tree_tropical2", 46, 14),
           obj("bamboo_cluster", 44, 28), obj("bush_dark", 8, 28),
           obj("statue", 34, 18), obj("totem", 38, 22), obj("totem_red", 36, 24),
           obj("tribal_shield", 32, 24), obj("log", 8, 32)],
  npcs=[npc("npc_lasan", 22, 16, facing="down"),
        npc("npc_tina", 26, 18, facing="down"),
        npc("npc_rini", 32, 28, facing="left"),
        npc("npc_penari", 18, 22, wander=True, facing="right")],
  landmarks=[lm("lm_rumah_panjang", "The Longhouse", 24, 16,
                "One roof, one long gallery, many family rooms behind it.", "house"),
             lm("lm_kampung_sungai", "River Village", 25, 12,
                "A village on stilts a few steps from the water.")],
  interactables=[
      ix("kl_pz_roof_site", "puzzle", 20, 16, target="pz_roof_plait",
         prompt="Help with the roof panels", sprite="textile_rack",
         when={"quest_active": "kl_01_rumah_panjang"}),
      ix("kl_pz_karungut_site", "puzzle", 26, 20, target="pz_karungut",
         prompt="Listen to the singing", sprite="drum",
         when={"quest_active": "kl_02_karungut"}),
      ix("kl_pick_seed", "pickup", 30, 22, target="bibit_padi_ladang",
         text="A handful of seed rice kept back for the dry fields."),
      ix("kl_col_bead", "pickup", 36, 22, target="col_manik_dayak"),
      ix("kl_col_handle", "pickup", 40, 20, target="col_ukiran_kecil_kl"),
      ix("kl_save_desa", "save", 22, 22),
      ix("kl_note_gallery", "note", 24, 18, title="The gallery",
         text="The gallery belongs to everybody. Meals, mending, meetings, music - all of it "
              "happens on this one long veranda."),
      ix("kl_hidden_below", "hidden", 46, 34, title="Under the House",
         text="Under the stilted floor there is a dry space used for storing boats and rattan, "
              "cool in the heat and quiet in the evening.",
         items=["rumpun_rotan"], culture="rumah_panjang")],
  collision=[])

M("kalimantan_sungai", "Sungai Besar", "kalimantan", (56, 40), "kalimantan", "stream",
  {"default": "JUNGLE",
   "rects": [rect("WATER", 0, 12, 56, 16), rect("SAND", 0, 28, 56, 4),
             rect("SAND", 0, 8, 56, 4), rect("JUNGLE", 0, 32, 56, 8),
             rect("DIRT", 6, 30, 20, 8), rect("PLANK", 38, 30, 14, 8)],
   "lines": [line("PATH", 6, 34, 50, 34, 3)],
   "blobs": [blob("REED", 24, 30, 4), blob("JUNGLE", 50, 6, 5), blob("JUNGLE", 6, 6, 5)]},
  objects=[obj("boat_dock_house", 12, 34), obj("dock", 20, 30), obj("canoe", 24, 12),
           obj("canoe", 30, 14, flip=True), obj("crate", 16, 32), obj("barrel", 18, 32),
           obj("basket", 42, 32), obj("drying_rack", 44, 32),
           obj("tree_tropical", 4, 34), obj("tree_tropical2", 34, 36),
           obj("tree_palm", 52, 36), obj("bamboo_cluster", 2, 30),
           obj("log", 48, 30), obj("rock_big", 36, 6), obj("reed_clump", 22, 30),
           obj("bridge_plank", 28, 30)],
  npcs=[npc("npc_bapa_udi", 16, 32, facing="right")],
  landmarks=[lm("lm_sungai", "The Big River", 28, 20,
                "The road of the interior: boats, timber, rattan and news all come down it.",
                "river")],
  interactables=[
      ix("kl_pz_river_site", "puzzle", 20, 30, target="pz_river_flow",
         prompt="Examine the channel", sprite="bridge_plank",
         when={"quest_active": "kl_03_sungai"}),
      ix("kl_note_river", "note", 24, 28, title="Boatman's note",
         text="Never swim after rain. If the water is brown and quick, the river is not yours."),
      ix("kl_col_damar", "pickup", 46, 34, target="col_damar"),
      ix("kl_save_river", "save", 18, 30),
      ix("kl_minigame_river", "minigame", 40, 30, prompt="Race downstream",
         minigame="nod", title="Downstream Timing", target="nod",
         text="Take the bends at the right moment.",
         data={"rounds": 3, "width": 92, "speed": 340,
               "themes": ["the current is fast!", "bend coming up!",
                          "the landing is in sight!"]},
         reward_cp=35),
      ix("kl_hidden_oxbow", "hidden", 52, 6, title="The Oxbow",
         text="An old loop of the river, cut off years ago, has become a still green pool "
              "full of fish and lily pads.",
         items=["ikan_kuning"], culture="hutan_kalimantan")],
  collision=[])

M("kalimantan_pasar", "Pasar Terapung", "kalimantan", (52, 36), "kalimantan", "waves",
  {"default": "WATER",
   "rects": [rect("PLANK", 14, 12, 24, 14), rect("WATER", 0, 0, 52, 36),
             rect("SAND", 0, 26, 14, 6), rect("DIRT", 12, 26, 28, 4)],
   "lines": [],
   "blobs": [blob("REED", 46, 28, 4)]},
  objects=[obj("dock", 20, 14), obj("dock", 30, 14), obj("boat_dock_house", 34, 26),
           obj("canoe", 10, 12), obj("canoe", 16, 10), obj("canoe", 24, 10),
           obj("canoe", 32, 10), obj("canoe", 40, 12, flip=True),
           obj("market_stall", 20, 18), obj("market_stall_blue", 26, 18),
           obj("food_stall", 32, 18), obj("crate", 18, 22), obj("barrel", 22, 22),
           obj("basket", 26, 22), obj("drying_rack", 30, 22),
           obj("tree_palm", 2, 28), obj("reed_clump", 44, 26)],
  npcs=[npc("npc_koki", 32, 22, facing="down"),
        npc("npc_pedagang", 20, 22, facing="down", wander=True),
        npc("npc_nelayan", 40, 14, facing="left")],
  landmarks=[lm("lm_pasar_terapung", "Floating Market", 26, 16,
                "The market happens from boats, before sunrise, and is gone by mid-morning.",
                "market")],
  interactables=[
      ix("kl_pz_soto_site", "puzzle", 30, 22, target="pz_soto_banjar",
         prompt="Help at the food stall", sprite="cooking_fire",
         when={"quest_active": "kl_06_soto"}),
      ix("kl_pz_logic_site", "puzzle", 18, 22, target="pz_pasar_logic",
         prompt="Question the boatmen", sprite="canoe",
         when={"quest_active": "kl_07_pasar_logic"}),
      ix("kl_note_floating", "note", 24, 16, title="Floating market notice",
         text="Boats tie up in rows. Sellers facing sellers, buyers alongside. "
              "When the light is strong, the market is already going home."),
      ix("kl_pick_thread", "pickup", 28, 20, target="benang_sasirangan",
         text="Strong thread used to tie cloth tightly before it goes into the dye."),
      ix("kl_pick_cinnamon", "pickup", 22, 20, target="bumbu_coto",
         text="Coriander, cumin and lemongrass, tied in a cloth."),
      ix("kl_col_sasirangan", "pickup", 34, 22, target="col_gelang_rotan"),
      ix("kl_save_market", "save", 26, 20)],
  collision=[])

M("kalimantan_hutan", "Rimba Kalimantan", "kalimantan", (54, 40), "kalimantan", "forest",
  {"default": "JUNGLE",
   "rects": [rect("MUD", 8, 24, 18, 12), rect("DIRT", 30, 20, 18, 12),
             rect("PATH", 4, 18, 46, 3), rect("WATER", 0, 0, 54, 4)],
   "blobs": [blob("GRASS", 28, 34, 6), blob("BAMBOO", 46, 8, 5), blob("TALLGRASS", 12, 10, 5)]},
  objects=[obj("tree_tropical", 6, 10), obj("tree_tropical2", 14, 8), obj("tree_tropical", 24, 10),
           obj("tree_fruit", 34, 8), obj("tree_tropical2", 44, 14), obj("tree_tropical", 50, 22),
           obj("tree_tropical", 4, 30), obj("tree_fruit", 20, 36), obj("tree_tropical2", 46, 34),
           obj("bamboo_cluster", 44, 10), obj("fern", 10, 20), obj("fern", 30, 26),
           obj("workshop", 36, 24), obj("rug_") if False else obj("easel_board", 34, 26),
           obj("barrel", 38, 26), obj("crate", 40, 26), obj("cave_mouth", 10, 14),
           obj("rock_big", 48, 28), obj("mushroom", 26, 30), obj("log", 32, 36),
           obj("totem", 44, 30), obj("totem_red", 42, 32), obj("tribal_shield", 40, 30)],
  npcs=[npc("npc_pengrajin", 36, 26, facing="left")],
  landmarks=[lm("lm_bengkel_hutan", "Forest Workshop", 36, 26,
                "A workbench under a lean-to: carving adzes, rattan, resin and half-finished work.",
                "workshop")],
  interactables=[
      ix("kl_pz_tools_site", "puzzle", 34, 26, target="pz_mandau_tools",
         prompt="Sort the workbench", sprite="easel_board",
         when={"quest_active": "kl_05_bengkel"}),
      ix("kl_note_carving", "note", 38, 28, title="Carver's mark",
         text="The shapes on these posts are abstract curves and hooks. In this game they are "
              "original drawings - no specific carving from any community is reproduced."),
      ix("kl_pick_resin", "pickup", 30, 28, target="getah_kemenyan",
         text="Lumps of resin that smell of smoke and sweetness."),
      ix("kl_col_carved", "pickup", 22, 32, target="col_damar"),
      ix("kl_save_hutan", "save", 26, 22),
      ix("kl_hidden_cave", "hidden", 10, 16, title="The Cold Cave",
         text="The cave mouth breathes cold air. Inside there are swallow nests high up and "
              "the sound of water somewhere behind the rock.",
         items=["obat_herbal"]),
      ix("kl_minigame_hornbill", "minigame", 28, 30, prompt="Watch the hornbills",
         minigame="nod", title="Hornbill Timing", target="nod",
         text="Note each bird as it crosses.",
         data={"rounds": 3, "width": 100, "speed": 300,
               "themes": ["one bird crossing!", "two more coming!",
                          "the flock is moving!"]},
         reward_cp=35)],
  collision=[])

# =============================================================== SULAWESI
M("sulawesi_desa", "Kampung Tongkonan", "sulawesi", (48, 40), "sulawesi", "highland",
  {"default": "HIGHLAND",
   "rects": [rect("GRASS", 0, 0, 48, 8), rect("PAVING", 16, 16, 16, 12),
             rect("FARM", 2, 26, 14, 8), rect("RICE", 32, 26, 14, 8),
             rect("PATH", 6, 22, 36, 3)],
   "lines": [line("PATH", 24, 8, 24, 22, 3), line("PATH", 24, 22, 24, 34, 3),
             line("PATH", 6, 22, 42, 22, 3)],
   "blobs": [blob("TALLGRASS", 42, 8, 5), blob("JUNGLE", 4, 12, 4)]},
  objects=[obj("tongkonan", 24, 12), obj("lumbung", 12, 18), obj("lumbung", 36, 18),
           obj("warung", 14, 28), obj("workshop", 34, 30), obj("stage", 24, 30),
           obj("well", 20, 20), obj("pot_plant", 22, 18), obj("basket", 26, 20),
           obj("cooking_fire", 30, 32), obj("easel_board", 20, 30),
           obj("tree_pine", 2, 20), obj("tree_pine", 44, 24),
           obj("flower_patch2", 18, 24), obj("fence_wood", 12, 32),
           obj("statue", 28, 16), obj("drum", 26, 30), obj("textile_rack", 36, 26)],
  npcs=[npc("npc_puang", 22, 18, facing="down"),
        npc("npc_rambu", 26, 24, facing="up"),
        npc("npc_yuliana", 14, 28, wander=True, facing="right")],
  landmarks=[lm("lm_tongkonan", "Ancestral House", 24, 15,
                "The saddle-roofed house of a family line, where the heirlooms are kept.",
                "house"),
             lm("lm_kampung_tongkonan", "Highland Village", 24, 22,
                "Houses facing north, rice stores raised on posts, and a road that climbs.")],
  interactables=[
      ix("sl_pz_gable_site", "puzzle", 22, 14, target="pz_tongkonan_carve",
         prompt="Examine the gable panels", sprite="easel_board",
         when={"quest_active": "sl_01_tongkonan"}),
      ix("sl_pick_kolintang", "pickup", 32, 26, target="batang_kolintang",
         text="One wooden bar of a tuned set, warm from the workshop."),
      ix("sl_col_kolintang", "pickup", 36, 20, target="col_keping_kolintang"),
      ix("sl_col_silk", "pickup", 32, 30, target="col_serat_sutra"),
      ix("sl_save_desa", "save", 20, 22),
      ix("sl_note_house", "note", 24, 17, title="The house faces north",
         text="Houses here face north. The heirlooms are kept inside, and the family builds "
              "and repairs the house together."),
      ix("sl_minigame_harvest", "minigame", 22, 30, prompt="Join the harvest game",
         minigame="nod", title="Harvest Timing", target="nod",
         text="The buffalo are coming in; keep time.",
         data={"rounds": 3, "width": 96, "speed": 320,
               "themes": ["the drums start!", "the crowd calls!", "one more round!"]},
         reward_cp=35)],
  collision=[])

M("sulawesi_pantai", "Pantai Bajo", "sulawesi", (52, 36), "sulawesi", "waves",
  {"default": "WATER",
   "rects": [rect("WATER", 0, 0, 52, 36), rect("PLANK", 8, 10, 36, 4),
             rect("PLANK", 8, 14, 4, 14), rect("PLANK", 24, 14, 4, 14),
             rect("PLANK", 40, 14, 4, 14), rect("PLANK", 8, 28, 36, 4),
             rect("SAND", 0, 26, 6, 10)],
   "lines": [],
   "blobs": [blob("REED", 46, 32, 3)]},
  objects=[obj("boat_dock_house", 14, 12), obj("boat_dock_house", 34, 12, flip=True),
           obj("canoe", 20, 20), obj("canoe", 28, 22, flip=True), obj("canoe", 44, 20),
           obj("dock", 20, 12), obj("dock", 32, 12), obj("basket", 16, 16),
           obj("drying_rack", 36, 16), obj("drying_rack_blue", 38, 16),
           obj("crate", 12, 16), obj("barrel", 14, 16),
           obj("tree_palm", 2, 30), obj("reed_clump", 46, 30), obj("rock_small", 6, 22)],
  npcs=[npc("npc_nelayan", 24, 24, facing="down"),
        npc("npc_penari", 34, 26, facing="up")],
  landmarks=[lm("lm_bajo", "The Stilt Village", 26, 20,
                "Houses and walkways standing over the water, with boats tied to the front step.",
                "village")],
  interactables=[
      ix("sl_pz_fish_site", "puzzle", 44, 22, target="pz_bajo_search",
         prompt="Read the fishers' reports", sprite="boat_dock_house",
         when={"quest_active": "sl_07_bajo"}),
      ix("sl_pz_dance_site", "puzzle", 34, 28, target="pz_pakarena",
         prompt="Watch the rehearsal", sprite="drum",
         when={"quest_active": "sl_05_pakarena"}),
      ix("sl_pick_shell", "pickup", 8, 30, target="col_kerang"),
      ix("sl_note_tide", "note", 26, 26, title="Tide note",
         text="The walkway floats. At high tide the first two planks are under water, "
              "and everybody simply steps down onto the deck of a boat."),
      ix("sl_save_pantai", "save", 26, 30),
      ix("sl_hidden_reef", "hidden", 48, 6, title="The Shallow Reef",
         text="Beyond the last walkway the water drops away and the reef begins - "
              "bright coral, small fish, and a broken anchor wedged in the coral.",
         items=["ikan_kuning"], culture="bajo_village")],
  collision=[])

M("sulawesi_pelabuhan", "Pelabuhan Makassar", "sulawesi", (52, 38), "sulawesi", "harbour",
  {"default": "PAVING",
   "rects": [rect("WATER", 0, 0, 52, 10), rect("SAND", 0, 10, 52, 3),
             rect("DIRT", 0, 13, 52, 25), rect("PLANK", 10, 14, 32, 10),
             rect("PATH", 4, 26, 44, 3)],
   "lines": [line("PLANK", 26, 10, 26, 26, 3), line("PATH", 4, 26, 48, 26, 3)],
   "blobs": [blob("JUNGLE", 48, 34, 4)]},
  objects=[obj("gate_keraton", 26, 32), obj("boat_dock_house", 12, 20),
           obj("dock", 18, 14), obj("dock", 34, 14), obj("canoe", 22, 8),
           obj("canoe", 30, 8, flip=True), obj("workshop", 40, 22),
           obj("market_stall", 8, 28), obj("market_stall_blue", 14, 28),
           obj("food_stall", 20, 28), obj("warung", 44, 28),
           obj("crate", 36, 20), obj("barrel", 38, 20), obj("basket", 24, 20),
           obj("easel_board", 30, 20), obj("tree_palm", 2, 32),
           obj("clock_tower", 46, 34), obj("lantern", 22, 24), obj("lantern", 30, 24)],
  npcs=[npc("npc_dg_naba", 38, 24, facing="left"),
        npc("npc_koki", 20, 26, facing="down"),
        npc("npc_pedagang", 12, 26, facing="right", wander=True),
        npc("npc_guru", 32, 28, facing="up")],
  landmarks=[lm("lm_pelabuhan", "Harbour Gate", 26, 28,
                "The old harbour gate: ships from everywhere tied up outside it for centuries.",
                "harbour"),
             lm("lm_benteng", "Stone Fort", 26, 34,
                "A stone fort built by the harbour kingdom, now a museum and archive.")],
  interactables=[
      ix("sl_pz_hull_site", "puzzle", 36, 22, target="pz_phinisi_hull",
         prompt="Examine the hull frame", sprite="boat_dock_house",
         when={"quest_active": "sl_02_phinisi"}),
      ix("sl_pz_coto_site", "puzzle", 20, 28, target="pz_coto",
         prompt="Help at the food stall", sprite="cooking_fire",
         when={"quest_active": "sl_04_coto"}),
      ix("sl_pz_lontara_site", "puzzle", 28, 30, target="pz_lontara_logic",
         prompt="Look at the archive table", sprite="easel_board",
         when={"quest_active": "sl_06_lontara"}),
      ix("sl_pz_ledger_site", "puzzle", 24, 20, target="pz_harbour_match",
         prompt="Open the cargo ledger", sprite="crate",
         when={"quest_active": "sl_08_pelabuhan"}),
      ix("sl_pick_plank", "pickup", 40, 20, target="papan_phinisi",
         text="A long board, already shaped by eye for a hull curve."),
      ix("sl_pick_pegs", "pickup", 42, 20, target="pasak_kayu",
         text="Hard wooden pegs. No iron in a wooden hull."),
      ix("sl_pick_coto_spice", "pickup", 16, 24, target="bumbu_coto"),
      ix("sl_pick_lontara", "pickup", 30, 30, target="naskah_lontara"),
      ix("sl_col_lontara", "pickup", 44, 30, target="col_kulit_lontara"),
      ix("sl_save_harbour", "save", 26, 24),
      ix("sl_note_ledger", "note", 24, 22, title="Ledger page",
         text="Silk from Sengkang, ships from Tanaberu, palm-leaf records from the archive, "
              "sago from the eastern islands, coffee from the highlands. Five cargoes, five places."),
      ix("sl_hidden_warehouse", "hidden", 48, 36, title="The Old Warehouse",
         text="Behind the fort an old warehouse is still standing, half empty, with a ramp "
              "down to the water and the smell of spice and rope.",
         items=["sou_perahu_mini"], culture="benteng_rotterdam")],
  collision=[])

M("sulawesi_bukit", "Bukit Minahasa", "sulawesi", (50, 38), "sulawesi", "highland",
  {"default": "HIGHLAND",
   "rects": [rect("CLIFF", 0, 0, 50, 5), rect("FARM", 6, 10, 18, 12),
             rect("FARM", 28, 12, 16, 10), rect("PATH", 4, 24, 42, 3),
             rect("TALLGRASS", 4, 28, 42, 8), rect("JUNGLE", 40, 4, 10, 16)],
   "blobs": [blob("CLIFF", 44, 30, 6), blob("JUNGLE", 6, 6, 5)]},
  objects=[obj("hut_coastal", 12, 14), obj("hut_coastal", 34, 16),
           obj("lumbung", 24, 20), obj("cooking_fire", 16, 18), obj("well", 22, 22),
           obj("drying_rack", 30, 20), obj("basket", 26, 24), obj("crate", 18, 24),
           obj("tree_pine", 2, 12), obj("tree_pine", 46, 10), obj("tree_fruit", 8, 30),
           obj("rock_big", 42, 32), obj("mountain_rock", 46, 26),
           obj("flower_patch", 20, 30), obj("fern", 30, 30), obj("fence", 12, 24)],
  npcs=[npc("npc_yuliana", 18, 20, facing="down", wander=True),
        npc("npc_pengembara", 28, 26, facing="up")],
  landmarks=[lm("lm_bukit", "Highland Gardens", 22, 20,
                "Slope gardens of vegetables, nutmeg and clove, planted along the hill "
                "instead of across it.", "gardens")],
  interactables=[
      ix("sl_note_slope", "note", 22, 24, title="Planting note",
         text="Plant along the slope, never across it: across the slope, the first heavy rain "
              "takes the soil with it."),
      ix("sl_pick_silk", "pickup", 34, 22, target="benang_sutra"),
      ix("sl_col_farm", "pickup", 12, 12, target="col_serat_sutra"),
      ix("sl_save_bukit", "save", 24, 26),
      ix("sl_hidden_spring", "hidden", 46, 36, title="The Mineral Spring",
         text="A spring comes out of the rock, warm and faintly sulphurous. The people here "
              "have built a stone basin to catch it and sit in it in the evening.",
         items=["obat_herbal"], culture="gotong_royong"),
      ix("sl_minigame_market", "minigame", 30, 28, prompt="Help with the harvest",
         minigame="nod", title="Highland Timing", target="nod",
         text="Bring the baskets down the slope in time.",
         data={"rounds": 3, "width": 100, "speed": 310,
               "themes": ["the baskets are full!", "careful on the slope!",
                          "almost at the barn!"]},
         reward_cp=35)],
  collision=[])

# ==================================================================== PAPUA
M("papua_desa", "Kampung Lembah", "papua", (48, 40), "papua", "highland",
  {"default": "HIGHLAND",
   "rects": [rect("DIRT", 12, 14, 24, 12), rect("FARM", 2, 28, 16, 8),
             rect("FARM", 30, 28, 16, 8), rect("PATH", 6, 22, 36, 3),
             rect("ASH", 14, 26, 8, 6)],
   "lines": [line("PATH", 24, 8, 24, 22, 3), line("PATH", 6, 22, 42, 22, 3)],
   "blobs": [blob("TALLGRASS", 40, 8, 5), blob("JUNGLE", 4, 10, 5), blob("CLIFF", 44, 34, 4)]},
  objects=[obj("honai_big", 22, 10), obj("honai", 14, 12), obj("honai", 32, 12),
           obj("honai", 12, 20), obj("cooking_fire", 20, 20), obj("drying_rack", 28, 20),
           obj("basket", 26, 22), obj("well", 18, 22), obj("pot_plant", 30, 22),
           obj("drum", 24, 24), obj("easel_board", 34, 22),
           obj("tree_pine", 2, 20), obj("tree_tropical", 46, 14),
           obj("flower_patch", 16, 26), obj("rock_big", 44, 28),
           obj("cooking_fire", 34, 32), obj("fence_wood", 10, 26)],
  npcs=[npc("npc_yosia", 20, 16, facing="down"),
        npc("npc_mama_lena", 26, 18, facing="down"),
        npc("npc_tomas", 22, 22, facing="up"),
        npc("npc_petrus", 30, 24, facing="left", wander=True)],
  landmarks=[lm("lm_honai", "The Round House", 22, 13,
                "A round house with a conical thatched roof and a low doorway, warm inside "
                "even when the morning is cold.", "house"),
             lm("lm_kampung_lembah", "Highland Hamlet", 24, 20,
                "Gardens, ditches and round houses in a cold, high valley.")],
  interactables=[
      ix("pp_pz_honai_site", "puzzle", 24, 12, target="pz_honai_build",
         prompt="Lay the roof thatch", sprite="easel_board",
         when={"quest_active": "pp_01_honai"}),
      ix("pp_pz_noken_site", "puzzle", 28, 18, target="pz_noken_knot",
         prompt="Look at the knots", sprite="basket",
         when={"quest_active": "pp_02_noken"}),
      ix("pp_pz_tifa_site", "puzzle", 22, 24, target="pz_tifa_pattern",
         prompt="Answer the drum", sprite="drum",
         when={"quest_active": "pp_04_tifa"}),
      ix("pp_pick_fibre", "pickup", 20, 20, target="serat_noken",
         text="Bark fibre, softened by soaking."),
      ix("pp_pick_sago", "pickup", 30, 20, target="sagu_kering",
         text="Dried sago starch in a leaf wrapper."),
      ix("pp_pick_skin", "pickup", 26, 24, target="anyaman_tifa",
         text="A scraped drum skin, warm from the rack."),
      ix("pp_col_noken", "pickup", 34, 20, target="col_noken_kecil"),
      ix("pp_save_desa", "save", 22, 18),
      ix("pp_note_house", "note", 22, 14, title="Round houses",
         text="The door is low so that you bow to enter, and the hearth in the middle keeps "
              "the house warm all night."),
      ix("pp_hidden_garden", "hidden", 46, 36, title="The Old Garden",
         text="An abandoned garden bed behind the ridge still grows sweet potato on its own, "
              "and a rope fence marks where the plot used to end.",
         items=["bibit_ubi"], culture="baliem_valley")],
  collision=[])

M("papua_lembah", "Lembah Baliem", "papua", (56, 40), "papua", "highland",
  {"default": "HIGHLAND",
   "rects": [rect("FARM", 6, 8, 20, 14), rect("FARM", 30, 8, 20, 14),
             rect("FARM", 6, 26, 20, 12), rect("FARM", 30, 26, 20, 12),
             rect("PATH", 2, 22, 52, 3), rect("WATER", 0, 0, 56, 3)],
   "lines": [line("PATH", 26, 3, 26, 38, 3), line("DIRT", 26, 22, 30, 3)],
   "blobs": [blob("CLIFF", 50, 6, 5), blob("JUNGLE", 4, 34, 4)]},
  objects=[obj("honai", 10, 6), obj("honai", 44, 6), obj("honai_big", 26, 6),
           obj("lookout_tower", 48, 14), obj("lookout_tower", 8, 34),
           obj("cooking_fire", 18, 24), obj("drying_rack", 34, 24),
           obj("basket", 22, 26), obj("crate", 30, 34), obj("fence_wood", 14, 24),
           obj("tree_pine", 2, 16), obj("tree_tropical", 52, 20),
           obj("rock_big", 42, 34), obj("mountain_rock", 46, 30),
           obj("flower_patch", 24, 34), obj("ditch") if False else obj("bridge_plank", 26, 22)],
  npcs=[npc("npc_guru", 20, 24, facing="down"),
        npc("npc_yosia", 34, 34, facing="left", wander=True)],
  landmarks=[lm("lm_lembah", "Valley Gardens", 26, 30,
                "Long garden beds drained by ditches, with sweet potato, taro and yam.",
                "gardens")],
  interactables=[
      ix("pp_pz_ditch_site", "puzzle", 26, 22, target="pz_valley_ditches",
         prompt="Examine the ditches", sprite="bridge_plank",
         when={"quest_active": "pp_05_lembah"}),
      ix("pp_pick_cuttings", "pickup", 38, 30, target="bibit_ubi",
         text="Vine cuttings for the next bed."),
      ix("pp_col_stone", "pickup", 46, 26, target="col_batu_lukis"),
      ix("pp_note_ditch", "note", 24, 26, title="Ditch note",
         text="The ground is wet but the roots still need air, so we dig ditches instead of "
              "walls. Water moves; the plants stay."),
      ix("pp_save_valley", "save", 24, 24),
      ix("pp_minigame_bridge", "minigame", 34, 24, prompt="Cross the rope bridge",
         minigame="nod", title="Rope Bridge Timing", target="nod",
         text="Step when the rope is steady.",
         data={"rounds": 3, "width": 94, "speed": 330,
               "themes": ["the bridge swings!", "one step at a time!",
                          "almost across!"]},
         reward_cp=35)],
  collision=[])

M("papua_danau", "Danau Sentani", "papua", (52, 38), "papua", "waves",
  {"default": "GRASS",
   "rects": [rect("WATER", 0, 0, 52, 16), rect("SAND", 0, 16, 52, 4),
             rect("GRASS", 0, 20, 52, 10), rect("DIRT", 6, 26, 40, 8),
             rect("JUNGLE", 40, 20, 12, 18)],
   "blobs": [blob("CLIFF", 46, 22, 5), blob("REED", 10, 20, 4)]},
  objects=[obj("hut_coastal", 14, 30), obj("hut_coastal", 30, 30),
           obj("boat_dock_house", 22, 24), obj("dock", 24, 20),
           obj("canoe", 20, 18), obj("canoe", 28, 18, flip=True),
           obj("drying_rack", 18, 32), obj("drying_rack_blue", 21, 32),
           obj("basket", 12, 28), obj("crate", 32, 28), obj("barrel", 34, 28),
           obj("easel_board", 26, 32), obj("cooking_fire", 16, 34),
           obj("tree_palm", 2, 34), obj("tree_tropical", 48, 30),
           obj("rock_big", 44, 22), obj("reed_clump", 8, 20), obj("fence", 30, 24)],
  npcs=[npc("npc_petrus", 24, 28, facing="down"),
        npc("npc_mama_lena", 16, 30, facing="right"),
        npc("npc_anak", 30, 26, wander=True)],
  landmarks=[lm("lm_danau_sentani", "Lake Shore", 26, 22,
                "A lake among hills, worked by the villages around it and famous for its "
                "painted bark cloth and canoes.", "lake")],
  interactables=[
      ix("pp_pz_lake_site", "puzzle", 22, 32, target="pz_sentani_find",
         prompt="Search the shore", sprite="basket",
         when={"quest_active": "pp_06_sentani"}),
      ix("pp_pz_barkcloth_site", "puzzle", 34, 32, target="pz_barkcloth",
         prompt="Help beat the bark cloth", sprite="textile_rack",
         when={"quest_active": "pp_07_kulit_kayu"}),
      ix("pp_pick_fish", "pickup", 18, 34, target="ikan_kuning",
         text="Fresh fish, ready for the soup pot."),
      ix("pp_col_fibre", "pickup", 40, 32, target="col_serat_sagu_kol"),
      ix("pp_note_lake", "note", 26, 24, title="Canoe note",
         text="Every canoe has a name and a family. If one is missing, the first question is "
              "always: whose canoe, and who took it out?"),
      ix("pp_save_lake", "save", 24, 26),
      ix("pp_hidden_paint", "hidden", 48, 34, title="The Painting Rock",
         text="A flat rock by the water is covered in old painted marks in red, white and "
              "black - geometric shapes only, made for this game and not copied from any "
              "specific design.",
         items=["serat_kulit_kayu"], culture="danau_sentani")],
  collision=[])

M("papua_hutan", "Hutan Pegunungan", "papua", (54, 40), "papua", "forest",
  {"default": "JUNGLE",
   "rects": [rect("CLIFF", 0, 0, 54, 5), rect("TALLGRASS", 6, 22, 40, 8),
             rect("PATH", 4, 18, 46, 3), rect("WATER", 46, 10, 6, 24),
             rect("ASH", 12, 30, 16, 6)],
   "blobs": [blob("MUD", 30, 32, 6), blob("BAMBOO", 42, 34, 4)]},
  objects=[obj("tree_tropical", 6, 10), obj("tree_tropical2", 16, 8), obj("tree_tropical", 26, 10),
           obj("tree_fruit", 36, 8), obj("tree_tropical2", 46, 18),
           obj("tree_tropical", 4, 32), obj("tree_fruit", 22, 36), obj("tree_tropical2", 40, 36),
           obj("cave_mouth", 14, 12), obj("rock_big", 34, 14), obj("mountain_rock", 30, 14),
           obj("log", 24, 26), obj("mushroom", 18, 28), obj("fern", 10, 20),
           obj("fern", 34, 28), obj("bamboo_cluster", 40, 32), obj("lookout_tower", 28, 18),
           obj("waterfall", 46, 14), obj("totem", 38, 28), obj("tribal_shield", 36, 30)],
  npcs=[npc("npc_pengembara", 28, 22, facing="down"),
        npc("npc_tomas", 34, 30, facing="left", wander=True)],
  landmarks=[lm("lm_hutan_papua", "Ridge Lookout", 28, 18,
                "A lookout on the ridge: forest, river and mountain, with hundreds of "
                "communities below it, each with its own language.", "ridge")],
  interactables=[
      ix("pp_pz_bird_site", "puzzle", 28, 20, target="pz_bird_logic",
         prompt="Read the watcher's notes", sprite="lookout_tower",
         when={"quest_active": "pp_08_burung"}),
      ix("pp_pick_plume", "pickup", 26, 24, target="col_bulu_molt",
         text="A plume lying on the forest floor, moulted naturally. Nothing was caught."),
      ix("pp_note_bird", "note", 30, 20, title="Watcher's rules",
         text="Watch with your eyes. Do not call, do not chase, do not collect. "
              "These birds were hunted almost to nothing once; that is why they are protected now."),
      ix("pp_save_hutan", "save", 26, 20),
      ix("pp_hidden_ridge", "hidden", 50, 36, title="Above the Waterfall",
         text="A path behind the waterfall leads up to a shelf of rock with a view down the "
              "whole valley, and to old markings that belong to nobody you can name.",
         items=["air_minum"], culture="burung_cenderawasih"),
      ix("pp_minigame_waterfall", "minigame", 44, 32, prompt="Cross by the waterfall",
         minigame="nod", title="River Crossing", target="nod",
         text="Cross when the water is between surges.",
         data={"rounds": 3, "width": 92, "speed": 350,
               "themes": ["the water is rising!", "wait for the gap!",
                          "one more step!"]},
         reward_cp=35)],
  collision=[])
