"""Sulawesi (chapter 5), Papua (chapters 6-7) and the ending."""
from content.qb import Q, o, DIALOGUES

# =============================================================== SULAWESI
Q("sl_01_tongkonan", "sulawesi", 5, "npc_puang",
  "The Saddle Roof",
  "The gable of the ancestral house is being recarved and the panels have to be turned "
  "the right way before the feast.",
  "Help restore the gable of the ancestral house.",
  [o("sl1_carve", "Turn the gable panels straight", "puzzle", "pz_tongkonan_carve"),
   o("sl1_lm", "Stand before the ancestral house", "landmark", "lm_tongkonan"),
   o("sl1_report", "Report to Puang", "talk", "npc_puang")],
  {"type": "talk", "npc": "npc_puang"},
  ["Fix a row at a time and leave it alone once it is right.",
   "Each turn of a panel is a quarter turn; none of them move.",
   "The house faces north, and the gable is above the door."],
  ["Do not touch the old carvings - only the new panels above the door need turning.",
   "The house itself has been in the family for generations; the gable, we renew.",
   "Help me line them up and then stand in front of the house. You should see it properly."],
  ["Straight and level. The house looks as it should again.",
   "The building belongs to the family line, not to one person. That is why we all work on it, "
   + "and why the heirlooms are kept inside it.",
   "Now look up at the roof - it sweeps to a point at both ends, like a saddle."],
  puzzle="pz_tongkonan_carve",
  interlude=["The panels are on the veranda of the house. Come and help me turn them."],
  rewards={"cp": 85, "items": ["ukiran_kayu", "col_keping_kolintang"],
           "culture": ["tongkonan"], "flags": ["sl_gable_fixed"]})

Q("sl_02_phinisi", "sulawesi", 5, "npc_dg_naba",
  "A Ship Without Nails",
  "The shipwright is laying the planking of a new hull and needs someone to check the "
  "curve pattern before the pegs go in.",
  "Lay out the planks of a wooden ship.",
  [o("sl2_wood", "Bring the planking", "collect", "papan_phinisi", 1),
   o("sl2_pegs", "Bring the wooden pegs", "collect", "pasak_kayu", 1),
   o("sl2_hull", "Lay the hull pattern", "puzzle", "pz_phinisi_hull"),
   o("sl2_report", "Show the shipwright the layout", "talk", "npc_dg_naba")],
  {"type": "talk", "npc": "npc_dg_naba"},
  ["No iron goes into a wooden hull - not one nail.",
   "The pattern narrows towards the keel and widens at the deck line.",
   "The bottom row is two separate points, not a solid line."],
  ["She will be two masts and about twenty metres. Not one nail in her.",
   "The planks are shaped by eye, then pegged and caulked with palm fibre.",
   "Check my layout before we peg it - once the pegs are in, the shape is decided."],
  ["That will hold. When the tide is high we will roll her down the beach and she will float.",
   "No paper drawings - the shape lives in the builder's head and the hands of the crew.",
   "That is why the knowledge is not written anywhere. It is passed from master to apprentice."],
  puzzle="pz_phinisi_hull",
  interlude=["The hull frame is on the beach. Bring the planking and check my layout."],
  requires=["sl_01_tongkonan"],
  rewards={"cp": 85, "items": ["pasak_kayu", "sou_perahu_mini", "layar_kain"],
           "culture": ["phinisi"], "flags": ["sl_hull_laid"]})

Q("sl_03_kolintang", "sulawesi", 5, "npc_rambu",
  "Wooden Bars and Mallets",
  "Rambu's kolintang group is one player short for a wedding, and the new player keeps "
  "striking the wrong bars.",
  "Learn a kolintang part for a wedding.",
  [o("sl3_bar", "Find a kolintang bar", "collect", "batang_kolintang", 1),
   o("sl3_listen", "Watch which bars are struck", "puzzle", "pz_kolintang_tune"),
   o("sl3_report", "Tell Rambu the group is ready", "talk", "npc_rambu")],
  {"type": "talk", "npc": "npc_rambu"},
  ["Watch the four bars that light up - they form a square in the middle.",
   "You may strike them in any order once you remember them.",
   "The spare bar is at the workshop behind the church."],
  ["A wedding needs music and our group is one short.",
   "Each of us covers a voice - melody, middle, bass. It only works as a group.",
   "Learn this pattern and you can stand in with us."],
  ["You will do. Play like that at the wedding and nobody will notice you are new.",
   "The bars are wooden, and the mallets are padded so the note rings instead of clattering.",
   "One set, three voices, played by three people. Just like the angklung, but with wood."],
  puzzle="pz_kolintang_tune",
  interlude=["The frame is set up behind the house. Stand at the bars and copy me."],
  requires=["sl_02_phinisi"],
  rewards={"cp": 85, "items": ["batang_kolintang", "sou_kolintang_mini"],
           "culture": ["kolintang"], "flags": ["sl_kolintang_ready"]})

Q("sl_04_coto", "sulawesi", 5, "npc_koki",
  "Coto for the Harbour",
  "The harbour cook has a queue of dockworkers and one pot of coto left to finish.",
  "Cook coto makassar for the harbour crowd.",
  [o("sl4_spice", "Bring the spice mix", "collect", "bumbu_coto", 1),
   o("sl4_cook", "Cook the coto", "puzzle", "pz_coto"),
   o("sl4_report", "Serve the harbour crowd", "talk", "npc_koki")],
  {"type": "talk", "npc": "npc_koki"},
  ["Peanut is what thickens the broth; it goes in grated, not whole.",
   "Spices are added after the meat is tender, never before.",
   "Stop the boil while the marker is inside the golden band."],
  ["Boat workers want one thing: soup they can eat standing up.",
   "The beef has been simmering since before dawn. Now the spice mix, then the peanut.",
   "The mix is at the spice stall by the harbour gate. Bring it, then stay and stir."],
  ["That is it. Eat a bowl and go look at the ships - the same water carried the spices here.",
   "Coriander and cumin did not grow on this island. They came by sea, and stayed.",
   "Every dish you have eaten on this journey is a record of a journey somebody else made."],
  puzzle="pz_coto",
  interlude=["The pot is at the harbour stall. Bring the spice mix and we will finish it."],
  requires=["sl_03_kolintang"],
  rewards={"cp": 85, "items": ["bumbu_coto", "col_serat_sutra"],
           "culture": ["coto_makassar"], "flags": ["sl_coto_cooked"]})

Q("sl_05_pakarena", "sulawesi", 5, "npc_penari",
  "The Unhurried Dance",
  "The dancers are rehearsing a Makassar welcome dance and the new dancers keep speeding "
  "up against the drum.",
  "Learn to follow the drum in a Makassar dance.",
  [o("sl5_beats", "Follow the drum", "puzzle", "pz_pakarena"),
   o("sl5_dance", "Dance one round", "minigame", "nod"),
   o("sl5_report", "Ask the dancer about the pace", "talk", "npc_penari")],
  {"type": "talk", "npc": "npc_penari"},
  ["The drum leads; you follow it. There is no counted beat.",
   "The beats come in pairs with a gap between them.",
   "Slow is correct - the dance is deliberately unhurried."],
  ["The new ones keep accelerating. You cannot hurry this dance.",
   "The steps are small, the hands carry the expression, and the drum decides when.",
   "Try it with me - follow the drum and do not count."],
  ["That was calm. That is what the dance is for: it tells a guest that nobody is in a hurry.",
   "Small steps, fan in hand, eyes up. Nothing is meant to look difficult.",
   "Harder than it looks, yes. That is the point of it."],
  puzzle="pz_pakarena",
  interlude=["We rehearse in the yard by the harbour. Stand at the back and follow the drum."],
  requires=["sl_04_coto"],
  rewards={"cp": 85, "items": ["sou_sutra_kecil", "col_kerang"],
           "culture": ["tari_pakarena"], "flags": ["sl_dance_learned"]})

Q("sl_06_lontara", "sulawesi", 5, "npc_guru",
  "The Palm Leaf Archive",
  "The teacher is sorting old palm-leaf records and one strip cannot be identified.",
  "Sort the old records in the village archive.",
  [o("sl6_logic", "Identify the record", "puzzle", "pz_lontara_logic"),
   o("sl6_report", "Return the strip to the teacher", "talk", "npc_guru")],
  {"type": "talk", "npc": "npc_guru"},
  ["Compare the lengths of the strips before the marks on them.",
   "The double mark appears on one record only.",
   "Whatever remains is the land record."],
  ["These are old records, written on palm leaf strips. Genealogy, law, diary, land.",
   "The labels rotted away, so we have to work them out again.",
   "One of them I cannot place. Read the marks and the lengths and tell me what it is."],
  ["The land record. That settles it - the boundary notes match what the elders remember.",
   "The script came from India long ago and was written on palm leaf with a sharp point.",
   "A written record is how a community argues with itself without losing the memory."],
  puzzle="pz_lontara_logic",
  interlude=["The strips are on the table in the archive. Look at them with me."],
  requires=["sl_05_pakarena"],
  rewards={"cp": 85, "items": ["naskah_lontara", "col_kulit_lontara"],
           "culture": ["lontara", "benteng_rotterdam"], "flags": ["sl_record_read"]})

Q("sl_07_bajo", "sulawesi", 5, "npc_nelayan",
  "Where the Fish Are",
  "The stilt village has had two empty mornings. The fishers' reports need reading to "
  "find where the fish have moved.",
  "Find the fishing ground from the fishers' reports.",
  [o("sl7_reach", "Walk the stilt village", "reach", "sulawesi_pantai"),
   o("sl7_find", "Mark the fishing ground", "puzzle", "pz_bajo_search"),
   o("sl7_report", "Give the fishers the position", "talk", "npc_nelayan")],
  {"type": "talk", "npc": "npc_nelayan"},
  ["West is the left side of the map and north is up.",
   "Fish were seen where the reef meets the deep channel.",
   "The channel runs south of the village, so the ground is between the two."],
  ["Two mornings, empty nets. The children will eat sago and we will eat sago.",
   "Everyone saw something different. One saw the shallows near the walkway, "
   + "another saw the reef edge, another the channel.",
   "Put it together for me - where should we go at first light?"],
  ["There. That is where we will be at first light.",
   "How did you work it? The shallows are close to the walkway, the reef meets the channel, "
   + "and north of the channel is where the fish school.",
   "You think like a fisher now. Take this shell, and this sash - for luck."],
  puzzle="pz_bajo_search",
  interlude=["Come out to the walkway with me. Bring the reports."],
  requires=["sl_06_lontara"],
  rewards={"cp": 85, "items": ["col_kerang"], "culture": ["bajo_village"],
           "flags": ["sl_fishing_ground"]})

Q("sl_08_pelabuhan", "sulawesi", 5, "npc_pedagang",
  "Ports and Cargo",
  "The last thing before the eastern crossing: the trader's cargo ledger has to be "
  "matched to the ports it came from.",
  "Sort the harbour ledger and take ship east.",
  [o("sl8_match", "Match each cargo to its port", "puzzle", "pz_harbour_match"),
   o("sl8_report", "Close the ledger with the trader", "talk", "npc_pedagang")],
  {"type": "talk", "npc": "npc_pedagang"},
  ["Silk comes from where it is woven, ships from where they are built.",
   "Sago travels by boat; it does not come down a mountain road.",
   "Each answer names a place you have already stood in."],
  ["The eastern boat leaves at high tide and I still have to close the ledger.",
   "Silk, ships, palm-leaf records, sago, coffee - five cargoes, five places.",
   "Match them for me and I will get you a place on the boat."],
  ["Ledger closed. The boat is at the end of the pier, sails already up.",
   "East of here the mountains get higher and the languages get more numerous.",
   "Go carefully, ask before you write, and take your time."],
  puzzle="pz_harbour_match",
  interlude=["The ledger is on the table at the end of the pier."],
  requires=["sl_07_bajo"],
  rewards={"cp": 110, "items": ["sou_perahu_mini"],
           "culture": ["sutra_sengkang", "sagu_maluku"],
           "flags": ["sl_ledger_done"], "unlock_region": "papua", "unlock_map": "papua_desa"},
  turnin_do={"chapter": 6})

# ================================================================== PAPUA
Q("pp_01_honai", "papua", 6, "npc_yosia",
  "A House for the Cold Nights",
  "The nights in the valley are cold and the thatch on the small house has to be "
  "rebuilt before the rains.",
  "Rebuild the roof of a round highland house.",
  [o("pp1_build", "Lay the roof thatch", "puzzle", "pz_honai_build"),
   o("pp1_lm", "Look at the round house", "landmark", "lm_honai"),
   o("pp1_report", "Report to Yosia", "talk", "npc_yosia")],
  {"type": "talk", "npc": "npc_yosia"},
  ["A honai roof is a cone of thatch - thick at the base and narrow at the top.",
   "The pattern widens with every row.",
   "The lowest three rows are filled in completely."],
  ["You came up from the coast? Then you felt how cold the night is here.",
   "These houses are round, with a roof of thatch that comes almost to the ground.",
   "The door is low, so you go in bowing. It keeps the heat in and the wind out."],
  ["Done. Now sit by the fire until your hands work again.",
   "The hearth sits in the middle of the floor and the smoke finds its way out through the thatch.",
   "Cold outside, warm inside. Everything about the shape is for that."],
  puzzle="pz_honai_build",
  interlude=["The thatch is stacked beside the house. Come up and copy the shape."],
  rewards={"cp": 90, "items": ["col_noken_kecil"], "culture": ["honai"],
           "flags": ["pp_roof_built"]})

Q("pp_02_noken", "papua", 6, "npc_mama_lena",
  "The Knotted Bag",
  "Mama Lena is making a noken and the knots have to be paired exactly, or the bag will "
  "not stretch evenly.",
  "Learn the knots of a noken bag.",
  [o("pp2_fibre", "Bring bark fibre", "collect", "serat_noken", 1),
   o("pp2_knots", "Pair the knots", "puzzle", "pz_noken_knot"),
   o("pp2_report", "Show Mama Lena the knots", "talk", "npc_mama_lena")],
  {"type": "talk", "npc": "npc_mama_lena"},
  ["Six knots, twelve cards - each knot has exactly one twin.",
   "Work across the top row first, then down.",
   "The fibre is in the smoke rack above the hearth."],
  ["The bag is not sewn and not woven on a loom. It is knotted.",
   "Pull it and it stretches; put a baby in it and it holds. That is the whole design.",
   "Bring the fibre and pair the knots with me - I have forgotten two of them."],
  ["Both right. Now the bag will hang straight on your back.",
   "You can carry sweet potato, firewood, or a baby in it, and it hangs from your head, "
   + "so your hands stay free.",
   "People have used these here for a very long time. It is not a small thing."],
  puzzle="pz_noken_knot",
  interlude=["The fibre is on the rack. Sit with me and pair the knots."],
  requires=["pp_01_honai"],
  rewards={"cp": 90, "items": ["serat_noken", "sou_noken_tas"],
           "culture": ["noken"], "flags": ["pp_knots_paired"]})

Q("pp_03_papeda", "papua", 6, "npc_petrus",
  "Sago and Fish",
  "Petrus is cooking papeda for the whole family and the sago has to go into the water "
  "at exactly the right moment.",
  "Cook papeda and fish soup.",
  [o("pp3_sago", "Bring the sago", "collect", "sagu_kering", 1),
   o("pp3_fish", "Bring fish for the soup", "collect", "ikan_kuning", 1),
   o("pp3_cook", "Cook the papeda", "puzzle", "pz_papeda"),
   o("pp3_report", "Eat with the family", "talk", "npc_petrus")],
  {"type": "talk", "npc": "npc_petrus"},
  ["Sago thickens all at once if the starch goes in too fast - stir while you pour.",
   "The fish soup simmers while the sago is being stirred.",
   "The sago is at the smoke rack and the fish is at the drying rack by the river."],
  ["You are hungry, so you are useful. Sit and stir.",
   "This is papeda: sago starch stirred into boiling water until it turns clear.",
   "The fish soup goes with it - yellow with turmeric, sour with lime."],
  ["Wrap it round the fork, dip it in the soup, and swallow. Do not chew, it does not need chewing.",
   "Sago comes from a palm that grows in wet ground where rice will not.",
   "So the food changes with the land. Rice where there are fields, sago where there is swamp."],
  puzzle="pz_papeda",
  interlude=["The pot is on the fire. Bring the sago and the fish and stir."],
  requires=["pp_02_noken"],
  rewards={"cp": 90, "items": ["sagu_kering", "gaung_papeda"],
           "culture": ["papeda"], "flags": ["pp_papeda_cooked"]})

Q("pp_04_tifa", "papua", 6, "npc_tomas",
  "Drum Call",
  "Tomas is carving a drum body and needs the call pattern again in his hands before "
  "the evening gathering.",
  "Learn the drum call for the evening gathering.",
  [o("pp4_skin", "Bring the drum skin", "collect", "anyaman_tifa", 1),
   o("pp4_call", "Answer the drum call", "puzzle", "pz_tifa_pattern"),
   o("pp4_report", "Play the call for Tomas", "talk", "npc_tomas")],
  {"type": "talk", "npc": "npc_tomas"},
  ["The call starts at the top corner and closes at the bottom.",
   "Six strikes, not eight - count them as they light up.",
   "Answer in any order; only the set of strikes matters."],
  ["The drum carries the beat for everything - singing, dancing, calling people in.",
   "You play sitting, with the drum on your lap or the ground, one hand on the skin.",
   "Watch my call and answer it back to me."],
  ["That is the call. Tonight they will hear it from the other side of the valley.",
   "This drum is carved from one piece of wood, and the skin is scraped thin and stretched.",
   "A good drum is loud without shouting. Take this small one - it is quiet, but it is a start."],
  puzzle="pz_tifa_pattern",
  interlude=["The drum is with me by the house. Watch, then answer."],
  requires=["pp_03_papeda"],
  rewards={"cp": 90, "items": ["anyaman_tifa", "sou_tifa_mini"],
           "culture": ["tifa"], "flags": ["pp_call_learned"]})

Q("pp_05_lembah", "papua", 6, "npc_guru",
  "Watering the Gardens",
  "The teacher is showing the garden ditches to the children, and one channel is turned "
  "the wrong way.",
  "Open the ditch to the sweet potato beds.",
  [o("pp5_reach", "Walk the valley gardens", "reach", "papua_lembah"),
   o("pp5_ditch", "Turn the ditches", "puzzle", "pz_valley_ditches"),
   o("pp5_seed", "Carry cuttings to the beds", "collect", "bibit_ubi", 1),
   o("pp5_report", "Report to the teacher", "talk", "npc_guru")],
  {"type": "talk", "npc": "npc_guru"},
  ["The stream enters near the top edge, one column across from the corner.",
   "These gardens are drained, not flooded; the ditch must keep running.",
   "The beds are in the bottom row, middle column."],
  ["In the highlands the ground is wet, but the water still has to move or the roots rot.",
   "So we dig ditches, not walls. That is different from the rice fields you saw on Java.",
   "Help me show the children where the water should run."],
  ["Now the beds are moist and not drowned. The children have seen why the ditch is there.",
   "The gardens here grow sweet potato, taro and yam - heavy crops, for a cold place.",
   "Different island, different field, different answer. All three work."],
  puzzle="pz_valley_ditches",
  interlude=["The ditches run behind the school. Bring the children - and turn the channels."],
  requires=["pp_04_tifa"],
  rewards={"cp": 90, "items": ["bibit_ubi", "col_batu_lukis"],
           "culture": ["baliem_valley", "rumah_kaki_seribu"], "flags": ["pp_ditch_open"]})

Q("pp_06_sentani", "papua", 6, "npc_petrus",
  "Something by the Lake",
  "A canoe has gone missing on the lake and the villagers' directions disagree.",
  "Find the missing canoe by the lake.",
  [o("pp6_lake", "Reach the lake shore", "reach", "papua_danau"),
   o("pp6_find", "Mark the place on the shore", "puzzle", "pz_sentani_find"),
   o("pp6_report", "Tell the village the canoe is safe", "talk", "npc_petrus")],
  {"type": "talk", "npc": "npc_petrus"},
  ["North is up on the search map, east is right.",
   "Start at the old canoe, then move east to the painted stones.",
   "The drying racks stand between the stones and the water."],
  ["The canoe drifted in the night. Nobody is hurt - it is the canoe we are missing.",
   "Four people saw it, four different directions.",
   "Take their words to the lakeshore and work out where it actually ended up."],
  ["It is there, tied up by the racks. The children will row it back tomorrow.",
   "Four witnesses, four directions, and all four were partly right. That is how talk works.",
   "Write down who saw what, not only what was true. Your notebook will be better for it."],
  puzzle="pz_sentani_find",
  interlude=["The lake is east of the village. Take the directions with you."],
  requires=["pp_05_lembah"],
  rewards={"cp": 90, "items": ["peta_lipat"], "culture": ["danau_sentani"],
           "flags": ["pp_canoe_found"]})

Q("pp_07_kulit_kayu", "papua", 6, "npc_mama_lena",
  "Beaten Cloth",
  "Mama Lena is making bark cloth and the sheet must be beaten flat before it dries, "
  "or the whole morning is wasted.",
  "Make bark cloth from start to finish.",
  [o("pp7_steps", "Order the steps of making bark cloth", "puzzle", "pz_barkcloth"),
   o("pp7_report", "Show Mama Lena the finished sheet", "talk", "npc_mama_lena")],
  {"type": "talk", "npc": "npc_mama_lena"},
  ["Bark is soaked before it is beaten, never the other way round.",
   "The sheet is dried flat; if it curls, it cannot be painted.",
   "Painting is the last step of all."],
  ["Cloth from bark. Not from a plant stem, not from an animal - from the inside of a tree.",
   "You strip it, soak it, and beat it until it spreads. Then you wait for it to dry.",
   "Tell me the order, then beat it with me."],
  ["Flat, soft and pale. Now it can be painted.",
   "Patterns belong to families here. What I paint, I was given the right to paint.",
   "That is why I will not copy somebody else's design onto it, and neither should you."],
  puzzle="pz_barkcloth",
  interlude=["The bark is soaking behind the house. Bring the mallet."],
  requires=["pp_06_sentani"],
  rewards={"cp": 90, "items": ["serat_kulit_kayu", "col_serat_sagu_kol", "sou_ukiran_papua"],
           "culture": ["kain_kulit_kayu", "asmat_carving"], "flags": ["pp_barkcloth_made"]})

Q("pp_08_burung", "papua", 6, "npc_pengembara",
  "Watching, Not Catching",
  "A bird watcher has been in the forest since before dawn and needs help reading the "
  "notes they brought back.",
  "Identify a bird from the watchers' notes.",
  [o("pp8_reach", "Walk into the forest", "reach", "papua_hutan"),
   o("pp8_notes", "Work out which bird was seen", "puzzle", "pz_bird_logic"),
   o("pp8_report", "Report the sighting", "talk", "npc_pengembara")],
  {"type": "talk", "npc": "npc_pengembara"},
  ["The notes are about behaviour, not about catching anything.",
   "One bird displays at dawn and folds its plumes into a fan.",
   "Choose the bird the notes describe."],
  ["I have walked up here for eleven mornings and seen almost nothing. That is bird watching.",
   "This morning: a display at first light, plumes up over the head, near the ridge.",
   "My handwriting in the dark is unreadable. Read it back to me."],
  ["The dawn bird, then. And nobody touched it, nobody caged it, nobody chased it.",
   "These birds were hunted almost to nothing for their feathers once - sold far away as decoration.",
   "Now they are protected here and by international trade rules. That is why we watch with our eyes only."],
  puzzle="pz_bird_logic",
  interlude=["Come up to the ridge with me at first light and read the notes."],
  closing="One more thing. Pak Hasan in Kampung Awal has been asking when you are coming "
          "home. Whatever that test of his is, I would go and take it.",
  requires=["pp_07_kulit_kayu"],
  rewards={"cp": 90, "items": ["col_bulu_molt"], "culture": ["burung_cenderawasih"],
           "flags": ["pp_bird_logged"]})

Q("pp_09_jejak", "papua", 7, "npc_penjaga",
  "The Keeping of Records",
  "Before the notebook is closed, the village keeper has one last test: everything "
  "you have recorded, asked back to you.",
  "Pass the final test and close the notebook.",
  [o("pp9_quiz", "Answer the keeper's questions", "puzzle", "pz_quiz_festival"),
   o("pp9_report", "Close the notebook with the keeper", "talk", "npc_penjaga")],
  {"type": "talk", "npc": "npc_penjaga"},
  ["Every question comes from something a person told you along the road.",
   "You may retry the test as many times as you like - it is a test, not a gate.",
   "The keeper will not ask about anything you never heard."],
  ["Sit. The notebook is nearly full, so there is one thing left to do.",
   "I will ask, and you will answer, and then we will both know what you actually learned.",
   "Do not worry about the score. Nobody has ever failed this by being honest."],
  ["Every answer right. Then close it and look at what you have written.",
   "You started with your grandmother's half-filled notebook. Now look at it.",
   "One more thing, outside. The whole village is waiting."],
  puzzle="pz_quiz_festival",
  interlude=["Sit here. We will do the questions one at a time."],
  requires=["pp_08_burung"],
  rewards={"cp": 150, "items": ["jurnal_nenek"], "culture": ["nusantara_intro", "gotong_royong"],
           "flags": ["story_complete"], "unlock_map": "prologue_festival"},
  turnin_do={"chapter": 7})

# ------------------------------------------------------------------ ending
DIALOGUES["ending_finale"] = {"start": "n1", "nodes": {
    "n1": {"speaker": "npc_penjaga",
           "lines": ["Stand here. Look around you for a moment.",
                     "There are people in this square from six islands. Nobody planned that; "
                     + "they came because you wrote to them."],
           "goto": "n2"},
    "n2": {"speaker": "npc_penjaga",
           "lines": ["Your grandmother wrote one line on the first page and left it at that.",
                     "It says: it is not one culture, and it is not a hundred separate ones.",
                     "It is people who trade, borrow, argue and celebrate together across the water."],
           "goto": "n3"},
    "n3": {"speaker": "npc_penjaga",
           "lines": ["She never finished the sentence. You have.",
                     "The notebook is closed. The islands are open. Go and look at them again - "
                     + "there is no hurry now.",
                     "And if somebody asks you what Indonesia is, hand them the notebook."],
           "do": {"set_flag": "ending_seen", "cp": 200},
           "goto": ""},
}}
