"""Prologue and Sumatra quest line (chapters 1-2)."""
from content.qb import Q, o, DIALOGUES

# ============================================================== PROLOGUE
Q("pg_01_notebook", "prologue", 1, "npc_penjaga",
  "The Notebook in the Store Room",
  "The village keeper remembers a cloth-bound notebook that belonged to your "
  "grandmother. Find the loose pages in the store room and sort them out.",
  "Sort grandmother's pages and take up her notebook.",
  [o("pg1_pages", "Match the six loose pages", "puzzle", "pz_notebook_pages"),
   o("pg1_report", "Show the notebook to Pak Penjaga", "talk", "npc_penjaga")],
  {"type": "talk", "npc": "npc_penjaga"},
  ["The pages are matched in pairs - look at the drawings, not the handwriting.",
   "Two pages have a pressed leaf inside them.",
   "The store room is inside the big house to the north."],
  ["Ah - you have come about your grandmother's things?",
   "She kept a notebook, and she always said it was not finished.",
   "It has been sitting in the store room since she stopped travelling. Pages everywhere."],
  ["You matched all six. And her hand is still on the first page.",
   "Then it is settled: the notebook travels again, and you are the one carrying it.",
   "Write down what people tell you. Their words, their names, their places."],
  puzzle="pz_notebook_pages",
  interlude=["The loose pages are in the store room - the room is the big house north of the square.",
             "Line them up by what is drawn on them."],
  rewards={"cp": 40, "items": ["jurnal_nenek", "lampu_minyak"],
           "culture": ["nusantara_intro", "notebook_habit"],
           "flags": ["has_notebook"]})

Q("pg_02_keberangkatan", "prologue", 1, "npc_pengembara",
  "What to Carry",
  "A traveller who has walked every region helps you pack for the road.",
  "Pack provisions with the traveller's help.",
  [o("pg2_supplies", "Finish packing the shoulder basket", "puzzle", "pz_gotong_royong"),
   o("pg2_reach", "Meet the traveller at the village gate", "reach", "desa_awal"),
   o("pg2_report", "Tell the traveller you are ready", "talk", "npc_pengembara")],
  {"type": "talk", "npc": "npc_pengembara"},
  ["A work day has an order: measure, cut, raise, tie, cover, sweep.",
   "Nothing is tied before the posts stand up.",
   "The gate is at the top of the village, where the path leaves the houses."],
  ["Packing is the same work as building - it has an order.",
   "Carry water, salt, a little sambal, and something to write with.",
   "The rest you can buy or be given along the way."],
  ["Good. Then you will not be the traveller who arrives empty-handed.",
   "One more thing: take the basket from the mending shed - the village filled it for you.",
   "Cloth, coffee, salt. Gifts. People will ask you where you are from."],
  puzzle="pz_gotong_royong",
  interlude=["The shed is west of the square. Bring the basket, and we will pack it together."],
  requires=["pg_01_notebook"],
  rewards={"cp": 40, "items": ["keranjang_isi", "bekal_jalan", "air_minum", "keranjang_kosong"],
           "culture": ["gotong_royong"], "flags": ["packed_basket"]})

Q("pg_03_net_mend", "prologue", 1, "npc_nelayan",
  "The Mended Net",
  "The fisherman's net has torn. He will take your help - but he will not take a nail.",
  "Mend the fishing net and earn the village's travel letter.",
  [o("pg3_net", "Mend the net", "puzzle", "pz_net_mend"),
   o("pg3_flags", "Collect the travel letter", "flag", "travel_letter_signed"),
   o("pg3_report", "Say goodbye at the village gate", "talk", "npc_nelayan")],
  {"type": "talk", "npc": "npc_nelayan"},
  ["Nets are tied with twine and a shuttle; iron has no business in a net.",
   "The mesh pattern is mirrored left and right.",
   "The jetty is on the west side of the village, past the boats."],
  ["You want to go inland? Then you will need this net mended first, and a letter.",
   "The letter says the next village should receive you. The keeper signs those.",
   "Here is the twine. My shuttle is on the bench."],
  ["That is a good mend - better than mine, and I have been doing it forty years.",
   "The keeper signed the letter while you were working. Take it.",
   "Inland, the roads climb. It is cold up there in the morning. Go carefully."],
  puzzle="pz_net_mend",
  interlude=["The twine is in your hand already. My bench is at the jetty, west of the houses."],
  requires=["pg_02_keberangkatan"],
  rewards={"cp": 60, "items": ["benang_jaring", "surat_izin", "tali_tambang"],
           "culture": ["kampung_home", "sambal"], "flags": ["travel_letter_signed"],
           "unlock_region": "sumatra", "unlock_map": "sumatra_desa"},
  turnin_do={"chapter": 2})

# ================================================================ SUMATRA
Q("sm_01_kampung", "sumatra", 2, "npc_aminah",
  "The Carved Wall",
  "Aminah is repainting the carved wall of the rumah gadang and cannot remember "
  "where each panel went. Help her put the patterns back in pairs.",
  "Learn the highland village and its carved house.",
  [o("sm1_wall", "Restore the carved wall", "puzzle", "pz_carving_memory"),
   o("sm1_house", "Study the rumah gadang", "landmark", "lm_rumah_gadang"),
   o("sm1_report", "Report to Aminah", "talk", "npc_aminah")],
  {"type": "talk", "npc": "npc_aminah"},
  ["Panels are paired by motif, not by size.",
   "The house itself is north of the market square.",
   "Stand close to the house until the journal entry is added."],
  ["You came up the new road? Then you are the traveller with the notebook.",
   "Look at this wall - the panels were taken down to be cleaned and now nobody agrees where they go.",
   "Help me match them and I will tell you about the house."],
  ["There - exactly. My mother would have put them the same way.",
   "This house belongs to the women of the family, you know. It is theirs, not the men's.",
   "Write that down before you forget it."],
  puzzle="pz_carving_memory",
  interlude=["The panels are stacked against the wall on the east side of the house."],
  rewards={"cp": 70, "items": ["col_ukiran_kecil"],
           "culture": ["rumah_gadang", "rumah_limas"],
           "flags": ["sm_wall_fixed"]})

Q("sm_02_rendang", "sumatra", 2, "npc_ida",
  "The Long Cook",
  "Ida is cooking for a wedding across the valley and needs the spice bundle finished "
  "and the pot watched.",
  "Cook rendang with Ida for a village wedding.",
  [o("sm2_spice", "Bring the spice bundle", "collect", "bumbu_rendang", 1),
   o("sm2_milk", "Bring the coconut milk", "collect", "mentega_kelapa", 1),
   o("sm2_cook", "Cook the rendang", "puzzle", "pz_rendang"),
   o("sm2_report", "Tell Ida it is ready", "talk", "npc_ida")],
  {"type": "talk", "npc": "npc_ida"},
  ["The spice bundle is on the market stall and the coconut milk is at the grinding shed.",
   "Pound the aromatics before they go anywhere near the meat.",
   "Coconut milk goes in after the spice paste, never before."],
  ["A wedding across the valley, which means rendang, which means I have been cooking since dawn.",
   "The spice bundle is still at the market stall and the coconut milk is at the grinder.",
   "Bring both, and then you can watch the pot - I need another pair of hands."],
  ["Nearly dry, and the colour is right. Sit down, you have earned a plate.",
   "Rendang is cooked this dry so it keeps. That is why it travels - and why weddings always have it."],
  puzzle="pz_rendang",
  interlude=["Everything is in the pot. Watch the fire with me - keep it steady."],
  requires=["sm_01_kampung"],
  rewards={"cp": 70, "items": ["bekal_jalan", "sambal_botol"], "culture": ["rendang"],
           "flags": ["sm_rendang_cooked"]})

Q("sm_03_saluang", "sumatra", 2, "npc_bujang",
  "A Melody in Bamboo",
  "Bujang cut a flute blank and lost the song that went with it. Play it back for him.",
  "Recover a saluang melody for the evening gathering.",
  [o("sm3_flute", "Find the bamboo blank", "collect", "bambu_saluang", 1),
   o("sm3_play", "Play the melody", "puzzle", "pz_saluang_song"),
   o("sm3_report", "Bring the melody to Bujang", "talk", "npc_bujang")],
  {"type": "talk", "npc": "npc_bujang"},
  ["The flute blank is on the bench by the bamboo clump.",
   "Press space (or click) as the note reaches the gold line.",
   "The melody starts slowly and speeds up in the middle - do not rush the start."],
  ["I cut a new saluang, and then I forgot how the song begins. Imagine!",
   "My teacher used to say the flute breathes for you if you let it.",
   "Take the blank and try. You do not need to be good, you need to listen."],
  ["That is it. That is the song.",
   "You know what is strange? You cannot get a good breath by breathing in and out normally.",
   "You push the air out while you breathe in through your nose. That is why a phrase can last so long."],
  puzzle="pz_saluang_song",
  interlude=["The blank is with the bamboo clump behind the house. Take it and try a phrase."],
  requires=["sm_02_rendang"],
  rewards={"cp": 70, "items": ["bambu_saluang"], "culture": ["saluang"],
           "flags": ["sm_flute_played"]})

Q("sm_04_ulos", "sumatra", 2, "npc_sari",
  "The Cloth for the Wedding",
  "Sari is weaving and the loom is set up with the wrong pattern. She needs the "
  "weave laid out before the thread tangles.",
  "Weave a cloth for the wedding and learn what the cloth means.",
  [o("sm4_thread", "Fetch the gold thread", "collect", "benang_songket", 1),
   o("sm4_weave", "Lay out the weaving pattern", "puzzle", "pz_ulos_pattern"),
   o("sm4_report", "Bring the cloth to Sari", "talk", "npc_sari")],
  {"type": "talk", "npc": "npc_sari"},
  ["The gold thread is with the trader at the market stall.",
   "Thread is woven; plastic and paint are not part of a loom.",
   "The pattern is mirrored top and bottom, with one line of light down the middle."],
  ["The wedding is tomorrow and the loom is fighting me.",
   "I have the yarn, but the pattern has to be laid out before the thread tangles.",
   "Will you fetch the gold thread from the trader? It is the last thing I need."],
  ["Good. Now it will hold.",
   "This kind of cloth is not sold in a shop - it is given. At a birth, at a wedding, at a funeral.",
   "Giving one is the same as saying a blessing out loud."],
  puzzle="pz_ulos_pattern",
  interlude=["The loom is under the lean-to. Sit at it and copy the pattern."],
  requires=["sm_03_saluang"],
  rewards={"cp": 70, "items": ["kain_ulos", "col_benang_emas"], "culture": ["ulos"],
           "flags": ["sm_ulos_woven"]})

Q("sm_05_talempong", "sumatra", 2, "npc_datuak",
  "The Wedding Music",
  "The elder has a talempong set for the wedding, but the players must be led. "
  "Learn which gongs to strike and when.",
  "Learn a talempong part for the wedding procession.",
  [o("sm5_listen", "Watch the gong pattern", "puzzle", "pz_talempong_pattern"),
   o("sm5_play", "Play the talempong", "minigame", "nod"),
   o("sm5_report", "Tell Datuak it went well", "talk", "npc_datuak")],
  {"type": "talk", "npc": "npc_datuak"},
  ["Watch which gongs light up, then strike the same ones.",
   "There are five of them, from top left to bottom right.",
   "The festival game at the square uses the same steady hand."],
  ["You have heard the flute and watched the cloth; now comes the music for the procession.",
   "The talempong is a set of small bronze gongs. One person cannot play a whole tune - "
   + "we strike, and the tune comes out between us.",
   "Learn the pattern, then try the procession game at the square."],
  ["Enough. The wedding will have its music.",
   "Small gongs like these travel well - we can carry the whole set to the next village. "
   + "A big bronze orchestra could never do that."],
  puzzle="pz_talempong_pattern",
  interlude=["Come to the frame of gongs behind the elders' house. I will show you the pattern."],
  requires=["sm_04_ulos"],
  rewards={"cp": 70, "items": ["col_talempong_chip"], "culture": ["talempong"],
           "flags": ["sm_talempong_played"]})

Q("sm_06_danau", "sumatra", 2, "npc_pedagang",
  "The Cargo that Went into the Lake",
  "A basket of goods slid off the trader's canoe. The villagers saw it drift - "
  "help the trader work out where it came ashore.",
  "Recover the trader's cargo from the lakeshore.",
  [o("sm6_lake", "Reach the lakeshore", "reach", "sumatra_danau"),
   o("sm6_search", "Find the cargo", "puzzle", "pz_danau_search"),
   o("sm6_cliff", "Look out over the water", "landmark", "lm_danau_toba"),
   o("sm6_report", "Return the cargo to the trader", "talk", "npc_pedagang")],
  {"type": "talk", "npc": "npc_pedagang"},
  ["The lake is up the western road from the village.",
   "The reeds are on the north side of the landing; the rocks are south.",
   "North is towards the top of the search picture."],
  ["Half my goods went into the lake this morning. Everybody saw it, nobody agrees where.",
   "A boy says the reeds caught it. The cake seller says it went past her stall.",
   "Walk up to the lake and work out where it actually came ashore, would you?"],
  ["My basket, my salt, my coffee - all dry inside.",
   "I have travelled this lake shore for twenty years and I would not have guessed that spot.",
   "You read the shore better than I do. That is worth a sack of beans."],
  puzzle="pz_danau_search",
  interlude=["Come up to the lake with me and look at the shore."],
  requires=["sm_05_talempong"],
  rewards={"cp": 70, "items": ["biji_kopi", "col_kopi_liar"], "culture": ["danau_toba"],
           "flags": ["sm_cargo_found"]})

Q("sm_07_piring", "sumatra", 2, "npc_penari",
  "The Harvest Dance",
  "The dance troupe is rehearsing for the harvest festival and the newest dancer "
  "keeps losing the order of the steps.",
  "Learn the order of the harvest plate dance.",
  [o("sm7_plates", "Find a pair of dance plates", "collect", "piring_tari", 1),
   o("sm7_steps", "Learn the dance steps", "puzzle", "pz_piring_steps"),
   o("sm7_report", "Dance one round with the troupe", "talk", "npc_penari")],
  {"type": "talk", "npc": "npc_penari"},
  ["A performance opens with a bow and closes with a bow.",
   "The quick steps come before the most difficult part, not after it.",
   "The plates are stepped on last - the plates are with the troupe, north of the square."],
  ["Hold these. Careful - they are real plates, not props.",
   "We dance with them in our palms, and at the end we step on them.",
   "The new dancer keeps starting with the hardest part. Help her sort the order."],
  ["Now she has it. One more rehearsal and the harvest festival will be ready.",
   "You should know where the dance comes from: it began as a thank-you for the rice harvest.",
   "That is why we still dance it when the field is cut."],
  puzzle="pz_piring_steps",
  interlude=["The troupe is north of the square, on the mat. Come and dance one round."],
  requires=["sm_06_danau"],
  rewards={"cp": 70, "items": ["piring_tari"], "culture": ["tari_piring"],
           "flags": ["sm_dance_learned"]})

Q("sm_08_pasar", "sumatra", 2, "npc_pengrajin",
  "Market Day in the Highlands",
  "The craftswoman needs her goods matched to the right stalls before the market opens, "
  "and she has something for you when it is done.",
  "Set up the market and take the road east.",
  [o("sm8_match", "Sort the goods to the stalls", "puzzle", "pz_pasar_match"),
   o("sm8_market", "Walk the market street at first light", "reach", "sumatra_desa"),
   o("sm8_report", "Say goodbye to the craftswoman", "talk", "npc_pengrajin")],
  {"type": "talk", "npc": "npc_pengrajin"},
  ["Thread belongs with weaving, chilli with spices, bronze with music.",
   "The market is at the eastern end of the village.",
   "Coffee is dried, not woven - it goes to the drying yard."],
  ["Market opens at first light and everything has to be in the right place.",
   "Gold thread, chilli, coffee, cloth, a little bronze - and I keep mixing them up.",
   "Help me sort them and I will tell the boatman that you need the eastern road."],
  ["Open on time. Look at that - the whole street trading.",
   "Take this scarf; it is not the best one I have made, but it is the one I can spare.",
   "The eastern road runs to the coast, then south along the water. Another island is waiting."],
  puzzle="pz_pasar_match",
  interlude=["The stalls are at the eastern end. Bring the goods and we will sort them."],
  requires=["sm_07_piring"],
  rewards={"cp": 90, "items": ["sou_kain_songket", "sou_kopi_pak", "col_benang_emas",
                                "sou_mini_rumah"],
           "culture": ["songket_palembang", "tari_saman"],
           "flags": ["sm_market_done"], "unlock_region": "java", "unlock_map": "java_desa"},
  turnin_do={"chapter": 3})
