"""Java (chapter 3) and Kalimantan (chapter 4) quest lines."""
from content.qb import Q, o

# =================================================================== JAVA
Q("jv_01_tumpeng", "java", 3, "npc_koki",
  "The Cone of Yellow Rice",
  "The cook is preparing tumpeng for a thanksgiving gathering and the rice keeps "
  "collapsing into a lump.",
  "Cook tumpeng for the village thanksgiving.",
  [o("jv1_ing", "Collect the ingredients", "collect", "bumbu_tumpeng", 1),
   o("jv1_cook", "Cook the tumpeng", "puzzle", "pz_tumpeng"),
   o("jv1_report", "Present the tumpeng to the cook", "talk", "npc_koki")],
  {"type": "talk", "npc": "npc_koki"},
  ["Turmeric is what makes the rice yellow; without it the cone is just rice.",
   "Rice is steamed before it is shaped - wet rice will not stand up.",
   "The side dishes are arranged after the cone stands, not before."],
  ["You are just in time to help, and I am not asking.",
   "Tonight is a syukuran - a thanksgiving - and there has to be tumpeng.",
   "The ingredients are at the market stall. Bring them and stay for the fire."],
  ["Now that is a mountain, not a lump. The tip goes to the eldest, you know.",
   "We cut the top first and give it away, then everybody eats the rest.",
   "Write that down: the shape is the mountain, and the mountain is what feeds us."],
  puzzle="pz_tumpeng",
  interlude=["The stove is behind the warung. Come and help me finish it."],
  rewards={"cp": 80, "items": ["bekal_jalan", "sambal_botol"], "culture": ["tumpeng"],
           "flags": ["jv_tumpeng_made"]})

Q("jv_02_batik", "java", 3, "npc_pengrajin",
  "Wax and Dye",
  "A batik maker needs the wax pen warmed and the pattern drawn before the dye bath "
  "is ready.",
  "Draw a batik pattern and learn how wax resists dye.",
  [o("jv2_wax", "Bring the wax", "collect", "lilin_batik", 1),
   o("jv2_pen", "Bring the wax pen", "collect", "canting", 1),
   o("jv2_draw", "Draw the pattern", "puzzle", "pz_batik"),
   o("jv2_report", "Show the cloth to the batik maker", "talk", "npc_pengrajin")],
  {"type": "talk", "npc": "npc_pengrajin"},
  ["Wax goes on the cloth cold-looking and molten-hot; it blocks the dye.",
   "The wax block is at the workshop and the pen is with the trader.",
   "The pattern repeats diagonally with filled corners."],
  ["Careful, the wax is hot. No - hotter than that. Good.",
   "This cloth will go into the dye bath twice. Whatever the wax covers stays light.",
   "Draw this pattern for me and I will show you why our patterns have names."],
  ["Now look at it against the light. Pale where the wax was, dark where the dye went.",
   "Some patterns are for weddings and some for everyday - it is not only decoration.",
   "That is why we say a batik has a name, not just a design."],
  puzzle="pz_batik",
  interlude=["The cloth is stretched on the frame. Sit down and draw with the pen."],
  requires=["jv_01_tumpeng"],
  rewards={"cp": 80, "items": ["col_lilin", "lilin_batik", "canting", "kain_merah"],
           "culture": ["batik"], "flags": ["jv_batik_drawn"]})

Q("jv_03_gamelan", "java", 3, "npc_ki_bagus",
  "Bronze Voices",
  "Ki Bagus is rehearsing the gamelan for the temple anniversary and needs a player "
  "who can keep time.",
  "Play in a gamelan rehearsal.",
  [o("jv3_mallet", "Fetch a mallet", "collect", "tabuh", 1),
   o("jv3_play", "Keep time with the ensemble", "puzzle", "pz_gamelan"),
   o("jv3_report", "Ask Ki Bagus about the tuning", "talk", "npc_ki_bagus")],
  {"type": "talk", "npc": "npc_ki_bagus"},
  ["Watch the drum; the whole ensemble follows it.",
   "The notes come in groups of four.",
   "You may miss a stroke - the rehearsal will not stop for you."],
  ["Sit here. Do not play yet - listen first.",
   "Each gamelan is tuned to suit itself, so a set is played together or not at all.",
   "We play for the temple anniversary. Keep time with the drum and you will be fine."],
  ["You kept time, and you did not rush. That is the whole art.",
   "Two tunings: one with five notes to the octave, one with seven. We use one at a time.",
   "Because a set is tuned as a set, you cannot mix instruments from two gamelan. Remember that."],
  puzzle="pz_gamelan",
  interlude=["The instruments are laid out in the pendopo. Sit at the saron and follow the drum."],
  requires=["jv_02_batik"],
  rewards={"cp": 80, "items": ["tabuh", "col_keping_gamelan"], "culture": ["gamelan"],
           "flags": ["jv_gamelan_played"]})

Q("jv_04_sawah", "java", 3, "npc_pak_tarno",
  "Water for the Terrace",
  "The irrigation gate has jammed and the lower terrace is drying out. Pak Tarno is "
  "up the hill with the other farmers.",
  "Open the water for the lowest terrace.",
  [o("jv4_map", "Walk the terrace path", "reach", "java_sawah"),
   o("jv4_water", "Turn the channels to the lowest field", "puzzle", "pz_sawah_water"),
   o("jv4_seed", "Carry seedlings to the lower field", "collect", "bibit_padi", 1),
   o("jv4_report", "Report to Pak Tarno", "talk", "npc_pak_tarno")],
  {"type": "talk", "npc": "npc_pak_tarno"},
  ["The spring is at the top left of the field map.",
   "Two channels must meet before any water can flow on.",
   "The dry field is the bottom right corner."],
  ["Every family here takes water in turn - that is how the terraces have survived.",
   "Today the gate jammed and the lowest field is drying.",
   "Go up the terrace path and open the channels again, then bring seedlings down."],
  ["Water is running to the lowest field. Good. Nobody's crop will fail today.",
   "You saw how the channels are shared? No single household owns that water.",
   "We keep the schedule together, and everyone eats. That is the whole system."],
  puzzle="pz_sawah_water",
  interlude=["The gate is up on the terrace path. Turn the channels until the water reaches the field."],
  requires=["jv_03_gamelan"],
  rewards={"cp": 80, "items": ["bibit_padi", "col_batu_candi"], "culture": ["sawah"],
           "flags": ["jv_water_open"]})

Q("jv_05_wayang", "java", 3, "npc_mbah_karto",
  "Behind the Screen",
  "The old puppeteer cannot perform tonight unless someone can answer his questions "
  "about the stories.",
  "Answer the puppeteer's questions about wayang.",
  [o("jv5_script", "Bring the story note", "collect", "naskah_wayang", 1),
   o("jv5_quiz", "Answer the puppeteer's questions", "puzzle", "pz_wayang_quiz"),
   o("jv5_report", "Sit with Mbah Karto for the story", "talk", "npc_mbah_karto")],
  {"type": "talk", "npc": "npc_mbah_karto"},
  ["Think about where the lamp is and where the audience sits.",
   "The puppets are in front of the screen; the shadows fall on the other side.",
   "The performance traditionally runs all night."],
  ["My eyes are tired, and my hands are still steady. It is the remembering that goes first.",
   "Tonight I need someone who can answer questions in front of the village.",
   "The story note is at the workshop. Bring it, and answer what I ask."],
  ["Correct, all three. Tonight you sit beside the screen and watch the shadows.",
   "The puppets are flat leather, and every one of them has a voice - the dalang gives it to them.",
   "That is what people come to hear: one person, a hundred voices, until morning."],
  puzzle="pz_wayang_quiz",
  interlude=["Sit here. I will ask the questions the way the village asks them."],
  requires=["jv_04_sawah"],
  rewards={"cp": 80, "items": ["naskah_wayang", "col_boneka_lidi"],
           "culture": ["wayang_kulit"], "flags": ["jv_wayang_quiz_passed"]})

Q("jv_06_angklung", "java", 3, "npc_rara",
  "One Note Each",
  "Rara is teaching a group of children angklung, and the group keeps falling apart "
  "because nobody waits their turn.",
  "Play angklung with the village children.",
  [o("jv6_order", "Learn how a group plays", "puzzle", "pz_angklung_order"),
   o("jv6_play", "Take part in the group game", "minigame", "nod"),
   o("jv6_report", "Tell Rara the group is ready", "talk", "npc_rara")],
  {"type": "talk", "npc": "npc_rara"},
  ["Each instrument makes one note, so the music only exists when many people play.",
   "Agree the beat before anybody shakes anything.",
   "Everyone stops together at the signal."],
  ["You cannot play angklung alone. That is the point of it.",
   "Each of these makes one note or one chord, so the tune is spread across thirty children.",
   "Help me teach them the order, then join the group game at the square."],
  ["Listen to them! Nobody is playing fast, and it works.",
   "This is how it is taught in school here - in a group, never in a practice room alone.",
   "One instrument, one note, everybody needed."],
  puzzle="pz_angklung_order",
  interlude=["The children are on the square with the instruments. Show them the order first."],
  requires=["jv_05_wayang"],
  rewards={"cp": 80, "items": ["sou_angklung_mini"], "culture": ["angklung"],
           "flags": ["jv_angklung_played"]})

Q("jv_07_candi", "java", 3, "npc_dewi",
  "The Stepped Mountain",
  "Dewi is copying the relief panels of the old temple for the museum and one panel "
  "row is out of order.",
  "Reconstruct the temple panel row and walk the galleries.",
  [o("jv7_reach", "Go to the temple grounds", "reach", "java_candi"),
   o("jv7_panels", "Turn the stone panels straight", "puzzle", "pz_candi_relief"),
   o("jv7_lm", "Walk the temple galleries", "landmark", "lm_candi"),
   o("jv7_report", "Give Dewi the panel notes", "talk", "npc_dewi")],
  {"type": "talk", "npc": "npc_dewi"},
  ["Click a panel to turn it a quarter; none of them need to move.",
   "Fix the top row first and then leave it alone.",
   "The galleries are walked clockwise, with the temple shape as the story."],
  ["Careful - do not touch the carvings, just look. We are copying, not restoring.",
   "The temple is built as a stepped mountain: you climb through galleries before the open terraces.",
   "Someone turned the panel blocks to clean behind them, and now the row is wrong."],
  ["The row is right again. Thank you.",
   "People walk it clockwise. Each level is a stage, and the reliefs are read as you climb.",
   "It was built in the eighth century, and it is still the largest Buddhist temple anywhere."],
  puzzle="pz_candi_relief",
  interlude=["Meet me at the temple grounds on the eastern road. Bring steady hands."],
  requires=["jv_06_angklung"],
  rewards={"cp": 80, "items": ["col_batu_candi"], "culture": ["borobudur"],
           "flags": ["jv_candi_fixed"]})

Q("jv_08_pasar_java", "java", 3, "npc_pedagang",
  "Before the Market Closes",
  "The trader's stall list is muddled and the market closes before noon. Sort the "
  "stalls, and the trader will point you to the crossing south.",
  "Sort the morning market and take the road south.",
  [o("jv8_match", "Match the stalls to their goods", "puzzle", "pz_javanese_market"),
   o("jv8_joglo", "Visit the village hall", "landmark", "lm_joglo"),
   o("jv8_report", "Say goodbye to the trader", "talk", "npc_pedagang")],
  {"type": "talk", "npc": "npc_pedagang"},
  ["Rice in a cone belongs to a food stall, wax to a batik stall.",
   "The padded mallet is used on bronze, not on cloth.",
   "The village hall is at the north end, where the gamelan is kept."],
  ["Half past five and the stalls already disagree about where they belong.",
   "Sort them for me? Rice, wax, mallets, seedlings, a fan - simple enough.",
   "Then I will tell you which road goes south to the river ports."],
  ["Open, and trading. Take this square of batik; the maker owes me a favour.",
   "South of here the road reaches the river country. Rivers, not roads, are the way in.",
   "Look for the long houses. You will know them when you see them."],
  puzzle="pz_javanese_market",
  interlude=["The market is on the square right now - come and help me sort it."],
  requires=["jv_07_candi"],
  rewards={"cp": 100, "items": ["sou_batik_syal", "sou_gamelan_mini"],
           "culture": ["rumah_joglo", "pasar_tradisional", "warung"],
           "flags": ["jv_market_done"], "unlock_region": "kalimantan", "unlock_map": "kalimantan_desa"},
  turnin_do={"chapter": 4})

# ============================================================ KALIMANTAN
Q("kl_01_rumah_panjang", "kalimantan", 4, "npc_lasan",
  "The Long Roof",
  "A storm took the roof panels off the longhouse gallery. Lasan is re-plaiting them "
  "and needs another pair of hands.",
  "Repair the longhouse roof and learn how it is shared.",
  [o("kl1_plait", "Plait a roof panel", "puzzle", "pz_roof_plait"),
   o("kl1_lm", "Walk the long gallery", "landmark", "lm_rumah_panjang"),
   o("kl1_report", "Report to Lasan", "talk", "npc_lasan")],
  {"type": "talk", "npc": "npc_lasan"},
  ["Rattan is soaked first so that it bends instead of cracking.",
   "The panel has a hollow centre and a complete outer ring.",
   "The gallery runs the whole length of the house."],
  ["You came up the river? Then you have seen the house from the water - one long roof, "
   + "the whole village under it.",
   "The storm took four panels off the gallery. We weave the replacements by hand.",
   "Help me finish one and then walk the gallery. It is longer than you think."],
  ["Good panel. That will hold the rain off for ten years.",
   "Every family has its own rooms along the gallery - and the gallery itself belongs to everyone.",
   "That is why we repair it together and nobody argues about whose roof it is."],
  puzzle="pz_roof_plait",
  interlude=["The rattan is soaking behind the house. Come and plait a panel with me."],
  rewards={"cp": 80, "items": ["rumpun_rotan", "col_gelang_rotan", "kayu_ukiran"],
           "culture": ["rumah_panjang"], "flags": ["kl_roof_fixed"]})

Q("kl_02_karungut", "kalimantan", 4, "npc_tina",
  "A Sung Story",
  "Tina is learning karungut - sung verses - and cannot hold the pulse through a long "
  "phrase.",
  "Learn the pulse of a sung verse.",
  [o("kl2_beats", "Keep the pulse of the verse", "puzzle", "pz_karungut"),
   o("kl2_report", "Sing a verse back to Tina", "talk", "npc_tina")],
  {"type": "talk", "npc": "npc_tina"},
  ["A sung story runs on a steady pulse - follow the drum, not your breath.",
   "The phrases are short, with a longer pause between them.",
   "You may miss a syllable and still finish the verse."],
  ["Listen. Do you hear how the words sit on the beat? Not on top of it - on it.",
   "My grandmother could sing a story for an hour without losing the thread.",
   "Help me keep the pulse through a whole verse. The drum will show you."],
  ["You held it. Now you know why the stories survive: the tune remembers the words for you.",
   "Advice, praise, the history of a place - all of it arrives singing.",
   "Write down what she told you, if you can. Words like that should not be lost."],
  puzzle="pz_karungut",
  interlude=["Sit with me on the gallery. The drum is here - keep the pulse with it."],
  requires=["kl_01_rumah_panjang"],
  rewards={"cp": 80, "items": ["anyaman_tifa"], "culture": ["karungut"],
           "flags": ["kl_karungut_sung"]})

Q("kl_03_sungai", "kalimantan", 4, "npc_bapa_udi",
  "The Blocked Channel",
  "A fallen tree is damming a side channel and the boats cannot reach the landing. "
  "The channel pieces must be turned so the flow finds its way again.",
  "Clear the channel so the river reaches the landing.",
  [o("kl3_reach", "Reach the upper river", "reach", "kalimantan_sungai"),
   o("kl3_flow", "Turn the channels", "puzzle", "pz_river_flow"),
   o("kl3_report", "Tell Bapa Udi the boats can come", "talk", "npc_bapa_udi")],
  {"type": "talk", "npc": "npc_bapa_udi"},
  ["The channel starts on the left bank, halfway up the map.",
   "A channel pointing away from the next one blocks the whole line.",
   "The landing is just above the middle of the right edge."],
  ["Rivers are our roads, and today our road is blocked. A tree came down in the night.",
   "Turn the channel pieces until the current runs to the landing again.",
   "Mind the bank - the mud goes deeper than your boots."],
  ["Boat coming in already. Listen to that engine.",
   "In the dry season the water drops and the channels change. We read the water the way "
   + "you read a road sign.",
   "Come back in the wet season and the whole map will be different."],
  puzzle="pz_river_flow",
  interlude=["Bring the boat up with me. The channel pieces are on the bank."],
  requires=["kl_02_karungut"],
  rewards={"cp": 80, "items": ["peta_lipat"], "culture": ["hutan_kalimantan"],
           "flags": ["kl_channel_open"]})

Q("kl_04_sasirangan", "kalimantan", 4, "npc_rini",
  "Tied and Dyed",
  "Rini is dyeing cloth for the river festival and one batch came out wrong because "
  "the ties were placed at random.",
  "Tie and dye a cloth the Banjar way.",
  [o("kl4_thread", "Bring the dye thread", "collect", "benang_sasirangan", 1),
   o("kl4_pattern", "Tie the pattern", "puzzle", "pz_sasirangan"),
   o("kl4_report", "Show Rini the dyed cloth", "talk", "npc_rini")],
  {"type": "talk", "npc": "npc_rini"},
  ["The ties form a ring around the middle of the cloth.",
   "Two of the tied squares sit in opposite corners.",
   "Count eight ties - not six, not ten."],
  ["Everything is tied, dyed and hung up - and the pattern is once again a mess.",
   "When the ties are placed at random you get a muddy cloth.",
   "Watch where I tie mine, then copy it. The thread is with the trader at the landing."],
  ["That is the pattern. Now look at the cloth after the dye has done its work.",
   "We call it sasirangan. The ties stay light, the rest goes deep.",
   "It used to be for ceremonies only. Now people wear it every day, and that is fine too."],
  puzzle="pz_sasirangan",
  interlude=["The dye pot is on the veranda. Watch the ties, then copy them."],
  requires=["kl_03_sungai"],
  rewards={"cp": 80, "items": ["benang_sasirangan", "sou_sasirangan"],
           "culture": ["sasirangan"], "flags": ["kl_cloth_dyed"]})

Q("kl_05_bengkel", "kalimantan", 4, "npc_pengrajin",
  "Tools of the Workshop",
  "The craftsperson's workbench was knocked over and every tool has to be paired with "
  "its partner before the day's work can start.",
  "Sort the workshop tools and learn what a mandau is for.",
  [o("kl5_tools", "Pair the workshop tools", "puzzle", "pz_mandau_tools"),
   o("kl5_report", "Ask the craftsperson about the blade", "talk", "npc_pengrajin")],
  {"type": "talk", "npc": "npc_pengrajin"},
  ["Each tool has exactly one twin on the bench.",
   "Six pairs, twelve items - work across a row at a time.",
   "The blade and its sheath belong together."],
  ["The bench went over in the night. Every tool is out of its place.",
   "A good blade is not sold in a market here - it is made, sharpened and passed down.",
   "Pair them up for me and I will show you the one I use every day."],
  ["There. The blade is for clearing brush, splitting rattan and cutting timber.",
   "The little knife on the sheath is the one that actually does the fine work.",
   "It goes to a funeral dressed as well, but that is not what makes it valuable. The work does."],
  puzzle="pz_mandau_tools",
  interlude=["Everything is piled on the bench. Start with the blade and its sheath."],
  requires=["kl_04_sasirangan"],
  rewards={"cp": 80, "items": ["pisau_serbaguna", "col_ukiran_kecil_kl"],
           "culture": ["mandau"], "flags": ["kl_tools_sorted"]})

Q("kl_06_soto", "kalimantan", 4, "npc_koki",
  "Soto from the River Market",
  "The cook at the floating market is short-handed and the spice pot is about to boil over.",
  "Cook soto for the river market.",
  [o("kl6_cook", "Cook the soto", "puzzle", "pz_soto_banjar"),
   o("kl6_market", "Visit the floating market", "reach", "kalimantan_pasar"),
   o("kl6_report", "Serve the first bowl", "talk", "npc_koki")],
  {"type": "talk", "npc": "npc_koki"},
  ["Broth first, whole spices second, lime only in the bowl.",
   "The whole spices are fished out before serving.",
   "The floating market is east along the water, past the long jetty."],
  ["Boats start arriving before dawn and they expect soup.",
   "Cinnamon, star anise, clove - whole, not ground. That is what makes the smell.",
   "Come and help, and then we will take a bowl to the floating market."],
  ["Drink it. That is the flavour of a river port: spices that came by ship, "
   + "beef from upriver, peanut from the market.",
   "Every ingredient here has travelled further than you have. Remember that when you eat."],
  puzzle="pz_soto_banjar",
  interlude=["The pot is on the stove at the stall. Come and taste as we go."],
  requires=["kl_05_bengkel"],
  rewards={"cp": 80, "items": ["bekal_jalan", "col_damar"],
           "culture": ["kuliner_kalimantan"], "flags": ["kl_soto_cooked"]})

Q("kl_07_pasar_logic", "kalimantan", 4, "npc_pedagang",
  "Which Boat Carries the Salt?",
  "Three boats lie at the landing and the trader's salt is on one of them. The boatmen "
  "will not say which.",
  "Work out which boat carries the salt.",
  [o("kl7_logic", "Work out which boat carries the salt", "puzzle", "pz_pasar_logic"),
   o("kl7_report", "Tell the trader where the salt is", "talk", "npc_pedagang")],
  {"type": "talk", "npc": "npc_pedagang"},
  ["The boat at the far end has only one neighbour.",
   "Boat A carries fruit, so the salt is not in A.",
   "Ask who is moored beside A."],
  ["I bought salt, and now three boatmen each swear somebody else has it.",
   "Boat A carries fruit. B is at the far end. C is moored next to the one with my salt.",
   "Work it out for me - I am too old to interrogate three liars before breakfast."],
  ["Boat C. Of course it is C.",
   "You would be a good market trader. Haggling is mostly noticing things.",
   "Take these; there is nothing in this life you cannot learn by watching a landing."],
  puzzle="pz_pasar_logic",
  interlude=["Come down to the landing and listen to them argue."],
  requires=["kl_06_soto"],
  rewards={"cp": 80, "items": ["keranjang_bahu", "sou_tas_rotan"],
           "culture": ["pasar_terapung"], "flags": ["kl_salt_found"]})

Q("kl_08_gantar", "kalimantan", 4, "npc_penari",
  "The Planting Dance",
  "The dancers are preparing a gantar for the planting season and the order of the "
  "movements keeps getting mixed up.",
  "Learn the planting dance and take the river road north.",
  [o("kl8_seed", "Bring seed for the planting", "collect", "bibit_padi_ladang", 1),
   o("kl8_steps", "Learn the planting steps", "puzzle", "pz_gantar_steps"),
   o("kl8_dance", "Dance the gantar with the troupe", "minigame", "nod"),
   o("kl8_report", "Say goodbye to the dancers", "talk", "npc_penari")],
  {"type": "talk", "npc": "npc_penari"},
  ["Nothing is planted before the ground is cleared; start there.",
   "Seed goes into a hole, never on top of the soil.",
   "The last movement presses the earth down over the seed."],
  ["We dance the planting before we plant - it is a rehearsal for the fields.",
   "The bamboo pole is the dibble stick, and the seed is real seed.",
   "Help me get the order right, then dance one round with us."],
  ["That is the whole cycle, danced in four minutes.",
   "The stick makes the hole, the hand drops the seed, the foot closes it. Then wait for rain.",
   "Take this, and take the northern road when you are ready. The sea is past the hills."],
  puzzle="pz_gantar_steps",
  interlude=["The dancers are on the long jetty. Bring seed and we will rehearse."],
  requires=["kl_07_pasar_logic"],
  rewards={"cp": 100, "items": ["bibit_padi_ladang", "sou_topi_anyaman", "col_manik_dayak"],
           "culture": ["tari_gantar", "tenun_ikat", "ukiran_dayak"],
           "flags": ["kl_planting_done"], "unlock_region": "sulawesi", "unlock_map": "sulawesi_desa"},
  turnin_do={"chapter": 5})
